import { Opportunity } from '@/types/opportunities';
import { OpportunityConnector, ConnectorConfig, ConnectorResult } from './types';
import * as cheerio from 'cheerio';

async function fetchAUTSAClubs(): Promise<Opportunity[]> {
  try {
    const res = await fetch('https://autsa.org.nz/clubs', {
      headers: { 'User-Agent': 'Gradual-App/2.0', Accept: 'text/html' },
    });
    if (!res.ok) return [];
    const html = await res.text();
    const $ = cheerio.load(html);
    const clubs: Opportunity[] = [];

    $('h2').each((_i, el) => {
      const name = $(el).text().trim();
      if (!name || name.length < 3 || name.length > 200) return;
      if (['Resources & Training', 'Important Documents', 'Check out our clubs!'].some(s => name.includes(s))) return;

      const parent = $(el).closest('div, section, article');
      const link = parent.find('a[href*="clubs-and-communities"]').attr('href') || '';
      const fullUrl = link.startsWith('http') ? link : link ? `https://www.autsa.org.nz${link}` : 'https://autsa.org.nz/clubs';

      clubs.push({
        id: `autsa_${name.toLowerCase().replace(/[^a-z0-9]/g, '_').slice(0, 60)}`,
        type: 'club',
        source: 'autsa',
        sourceId: name,
        sourceUrl: fullUrl,
        canonicalUrl: fullUrl,
        title: name,
        organization: 'AUT Students\' Association (AUTSA)',
        organizationUrl: 'https://autsa.org.nz',
        description: `${name} is a student club at Auckland University of Technology. Join to connect with like-minded students, build skills, and get involved on campus.`,
        location: 'Auckland, New Zealand',
        locationType: 'onsite',
        city: 'Auckland',
        country: 'New Zealand',
        tags: ['club', 'student', 'aut', 'auckland'],
        category: 'Student Clubs',
        url: fullUrl,
        applicationType: 'external',
        status: 'active',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      });
    });
    return clubs;
  } catch (err) {
    console.error('[ClubsConnector] AUTSA scrape failed:', err);
    return [];
  }
}

function getCuratedClubs(): Opportunity[] {
  const now = Date.now();
  const day = 24 * 60 * 60 * 1000;
  return [
    {
      id: 'club_uoa_comsci_society',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_comsci',
      title: 'University of Auckland ComSci Society',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/UOACS',
      description: 'UoA\'s computer science club hosting coding workshops, tech talks from industry professionals, hackathons, LAN parties, and study groups. Open to all students interested in technology regardless of major.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['computer-science', 'programming', 'hackathons', 'workshops', 'technology', 'networking'],
      categoryTags: ['academic', 'technology'],
      skills: ['programming', 'networking', 'teamwork'],
      industries: ['Technology', 'Software'],
      category: 'Technology',
      url: 'https://linktr.ee/UOACS',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 5 * day).toISOString(),
      benefits: ['Free workshops', 'Industry networking', 'Hackathon access', 'Mentorship'],
    },
    {
      id: 'club_uoa_wdcc',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_wdcc',
      title: 'Web Development & Consulting Club (WDCC)',
      organization: 'University of Auckland',
      organizationUrl: 'https://wdcc.co.nz/',
      description: 'Build real websites for real clients while learning web development. Projects use React, Next.js, and modern frameworks. Gain team-based development experience and build a real portfolio.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      isRemote: true,
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['web-development', 'react', 'nextjs', 'consulting', 'portfolio'],
      skills: ['react', 'javascript', 'web-development', 'teamwork', 'git'],
      industries: ['Technology', 'Web Development'],
      category: 'Technology',
      url: 'https://wdcc.co.nz/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      benefits: ['Real client projects', 'Portfolio building', 'Industry mentors'],
    },
    {
      id: 'club_uoa_sesa',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_sesa',
      title: 'Software Engineers Student Association (SESA)',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/sesa.uoa',
      description: 'The student association for software engineering students at UoA. Organises industry visits, career panels, project showcases, study sessions, and social events connecting students with tech employers.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['software-engineering', 'programming', 'career', 'networking', 'industry'],
      skills: ['software-engineering', 'programming', 'teamwork'],
      industries: ['Technology', 'Software Engineering'],
      category: 'Technology',
      url: 'https://linktr.ee/sesa.uoa',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 8 * day).toISOString(),
      benefits: ['Industry connections', 'Career panels', 'Study support'],
    },
    {
      id: 'club_uoa_data_science',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_dsc',
      title: 'University of Auckland Data Science Club',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/uoadsc',
      description: 'For students passionate about data science, machine learning, and AI. Runs Kaggle competitions, study groups, guest lectures from industry, and hands-on projects with real datasets.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      isRemote: true,
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['data-science', 'machine-learning', 'ai', 'python', 'kaggle'],
      skills: ['python', 'data-analysis', 'machine-learning', 'statistics'],
      industries: ['Data Science', 'Technology'],
      category: 'Data & Analytics',
      url: 'https://linktr.ee/uoadsc',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 10 * day).toISOString(),
      benefits: ['Kaggle competitions', 'Industry speakers', 'Project experience'],
    },
    {
      id: 'club_uoa_case_club',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_case_club',
      title: 'University of Auckland Case Club',
      organization: 'University of Auckland',
      organizationUrl: 'https://uoacaseclub.co.nz',
      description: 'Auckland\'s top case competition club. Hosts Baker Tilly, ZURU, Kearney, Energy Centre, and Juncture case competitions. Open to all degrees — build analytical thinking, teamwork, and presentation skills.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['case-competition', 'business', 'consulting', 'strategy', 'presentation'],
      skills: ['business-analysis', 'presentation', 'strategy', 'teamwork'],
      industries: ['Consulting', 'Business', 'Finance'],
      category: 'Business',
      url: 'https://uoacaseclub.co.nz',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      benefits: ['Case competition access', 'Industry judges', 'Networking'],
    },
    {
      id: 'club_uoa_startup_club',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_startup',
      title: 'StartUp Club NZ',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/startupclubnz',
      description: 'For aspiring entrepreneurs. Hosts pitch nights, startup workshops, founder talks, and connects members with mentors from the NZ startup ecosystem. Open to students from all faculties.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['entrepreneurship', 'startups', 'business', 'networking', 'pitching'],
      skills: ['entrepreneurship', 'pitching', 'business-planning', 'networking'],
      industries: ['Startups', 'Technology', 'Business'],
      category: 'Entrepreneurship',
      url: 'https://linktr.ee/startupclubnz',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 7 * day).toISOString(),
      benefits: ['Pitch nights', 'Founder mentorship', 'Startup ecosystem access'],
    },
    {
      id: 'club_uoa_robotics',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_aura',
      title: 'Auckland University Robotics Association (AURA)',
      organization: 'University of Auckland',
      organizationUrl: 'https://aura.org.nz/',
      description: 'Build robots, compete in challenges, and learn electronics and embedded programming. AURA runs workshops on Arduino, ROS, 3D printing, and hosts inter-university robotics competitions.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['robotics', 'engineering', 'electronics', 'arduino', 'programming'],
      skills: ['robotics', 'electronics', 'programming', 'engineering'],
      industries: ['Engineering', 'Robotics', 'Technology'],
      category: 'Engineering',
      url: 'https://aura.org.nz/',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 12 * day).toISOString(),
      benefits: ['Robotics competitions', 'Workshop access', 'Lab access'],
    },
    {
      id: 'club_uoa_women_business',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_wib',
      title: 'University of Auckland Women in Business',
      organization: 'University of Auckland',
      organizationUrl: 'https://linkin.bio/uoawomeninbusiness',
      description: 'Empowering women in commerce and business at UoA. Hosts employer panels, mentorship pairing, career workshops, and networking events with leading NZ businesses. Open to all genders as allies.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['women-in-business', 'networking', 'mentorship', 'career', 'diversity'],
      skills: ['networking', 'leadership', 'business'],
      industries: ['Finance', 'Consulting', 'Management'],
      category: 'Business',
      url: 'https://linkin.bio/uoawomeninbusiness',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 9 * day).toISOString(),
      benefits: ['Mentorship', 'Employer networking', 'Leadership development'],
    },
    {
      id: 'club_aut_csea',
      type: 'club',
      source: 'curated',
      sourceId: 'aut_csea',
      title: 'AUT Computer Science & Engineering Association (CSEA)',
      organization: 'AUT Students\' Association (AUTSA)',
      organizationUrl: 'https://www.autsa.org.nz/clubs-and-communities/aut-computer-science-%26-engineering-association',
      description: 'AUT\'s CS and engineering student society. Hosts coding challenges, tech talks, industry visits, project showcases, and social events. Connects AUT tech students with employers and alumni.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['computer-science', 'engineering', 'aut', 'programming', 'networking'],
      skills: ['programming', 'engineering', 'teamwork'],
      industries: ['Technology', 'Engineering'],
      category: 'Technology',
      url: 'https://www.autsa.org.nz/clubs-and-communities/aut-computer-science-%26-engineering-association',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 11 * day).toISOString(),
      benefits: ['Industry connections', 'Coding challenges', 'Social events'],
    },
    {
      id: 'club_aut_startup',
      type: 'club',
      source: 'curated',
      sourceId: 'aut_startup',
      title: 'AUT Startup Club',
      organization: 'AUT Students\' Association (AUTSA)',
      organizationUrl: 'https://www.autsa.org.nz/clubs-and-communities/aut-startup-club',
      description: 'For AUT students interested in entrepreneurship and innovation. Hosts idea jams, pitch practice, startup founder fireside chats, and connects with AUT\'s entrepreneurship programs.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['entrepreneurship', 'startups', 'innovation', 'aut', 'pitching'],
      skills: ['entrepreneurship', 'pitching', 'innovation'],
      industries: ['Startups', 'Business'],
      category: 'Entrepreneurship',
      url: 'https://www.autsa.org.nz/clubs-and-communities/aut-startup-club',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 13 * day).toISOString(),
      benefits: ['Pitch practice', 'Founder mentorship', 'Innovation workshops'],
    },
    {
      id: 'club_uoa_gdg',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_gdg',
      title: 'Google Developer Groups on Campus (UoA)',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/gdgcuoa',
      description: 'Official Google Developer Group at UoA. Learn about Google technologies — Android, Cloud, Firebase, TensorFlow, Flutter. Workshops, speaker series, and access to Google developer resources.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      isRemote: true,
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['google', 'android', 'cloud', 'firebase', 'flutter', 'developer'],
      skills: ['android', 'cloud-computing', 'machine-learning', 'flutter'],
      industries: ['Technology', 'Software'],
      category: 'Technology',
      url: 'https://linktr.ee/gdgcuoa',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      benefits: ['Google resources', 'Tech workshops', 'Developer community'],
    },
    {
      id: 'club_uoa_impact_consulting',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_icg',
      title: 'Impact Consulting Group',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/ImpactConsultingGroup.UoA',
      description: 'Pro-bono consulting for non-profits and social enterprises. Gain real consulting experience solving problems for community organisations while building analytical and communication skills.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      isRemote: true,
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['consulting', 'non-profit', 'social-impact', 'strategy', 'teamwork'],
      skills: ['consulting', 'strategy', 'data-analysis', 'presentation'],
      industries: ['Consulting', 'Non-profit'],
      category: 'Business',
      url: 'https://linktr.ee/ImpactConsultingGroup.UoA',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 7 * day).toISOString(),
      benefits: ['Real consulting projects', 'Client experience', 'CV builder'],
    },

    // ── UoA Academic & Specialist ──────────────────────────────────────

    {
      id: 'club_uoa_law_students',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_aulss',
      title: 'Auckland University Law Students Society (AULSS)',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/aucklandlawschool',
      description: 'The largest student society at UoA, representing all law students. AULSS organises mooting competitions, networking evenings with top-tier law firms, career panels, and social events throughout the year.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['law', 'networking', 'careers', 'mooting', 'student'],
      skills: ['legal-skills', 'networking', 'public-speaking'],
      industries: ['Law'],
      category: 'Law',
      url: 'https://linktr.ee/aucklandlawschool',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 2 * day).toISOString(),
      benefits: ['Networking events', 'Career panels', 'Mooting competitions', 'Social events'],
    },
    {
      id: 'club_uoa_commerce',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_aucsa',
      title: 'Auckland University Commerce Students\' Association (AUCSA)',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/Aucsa',
      description: 'The representative body for commerce students at UoA. AUCSA runs employer meet-and-greets, professional development workshops, inter-faculty sports, and an annual ball that brings together hundreds of commerce students.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['commerce', 'business', 'networking', 'careers', 'accounting', 'finance'],
      skills: ['networking', 'leadership', 'business'],
      industries: ['Finance', 'Accounting', 'Business'],
      category: 'Business',
      url: 'https://linktr.ee/Aucsa',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      benefits: ['Employer networking', 'Professional workshops', 'Annual ball'],
    },
    {
      id: 'club_uoa_medical_students',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_aumsa',
      title: 'Auckland University Medical Students\' Association (AUMSA)',
      organization: 'University of Auckland',
      organizationUrl: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      description: 'Represents medical students across all years of study at UoA\'s Faculty of Medical and Health Sciences. AUMSA provides academic support, clinical placement advice, wellbeing initiatives, and social events to build community among future doctors.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['medicine', 'health', 'careers', 'wellbeing', 'academic'],
      skills: ['clinical-skills', 'leadership', 'communication'],
      industries: ['Healthcare', 'Medicine'],
      category: 'Health & Medicine',
      url: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 5 * day).toISOString(),
      benefits: ['Academic support', 'Wellbeing resources', 'Clinical placement advice'],
    },
    {
      id: 'club_uoa_psychology',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_aupsa',
      title: 'Auckland University Psychology Students\' Association (AUPSA)',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/AUPSAuoa',
      description: 'Connects psychology students at all levels through study groups, research seminars, career panels with practising psychologists, and social events. AUPSA also advocates for student interests within the School of Psychology.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['psychology', 'research', 'mental-health', 'academic', 'careers'],
      skills: ['research', 'communication', 'critical-thinking'],
      industries: ['Psychology', 'Healthcare', 'Research'],
      category: 'Health & Medicine',
      url: 'https://linktr.ee/AUPSAuoa',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 8 * day).toISOString(),
      benefits: ['Study groups', 'Research seminars', 'Career panels'],
    },
    {
      id: 'club_uoa_women_in_science',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_auws',
      title: 'Auckland University Women in Science (AUWS)',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/auws.uoa',
      description: 'Supports and empowers women and gender minorities in STEM fields at UoA. AUWS hosts mentoring programmes, lab tours, speaker events with women in industry, and advocacy campaigns to close the gender gap in science.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['women-in-stem', 'science', 'diversity', 'mentoring', 'advocacy'],
      skills: ['leadership', 'networking', 'advocacy'],
      industries: ['Science', 'Research', 'Technology'],
      category: 'Science',
      url: 'https://linktr.ee/auws.uoa',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      benefits: ['Mentoring programme', 'Industry speaker events', 'Lab tours'],
    },
    {
      id: 'club_uoa_beta_alpha_psi',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_bap',
      title: 'Beta Alpha Psi — UoA Chapter',
      organization: 'University of Auckland',
      organizationUrl: 'https://bapuoa.org',
      description: 'The UoA chapter of the international honour society for accounting, finance, and information systems students. Members gain access to Big Four networking events, professional development workshops, and community service opportunities.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['accounting', 'finance', 'honour-society', 'networking', 'professional'],
      skills: ['accounting', 'networking', 'leadership'],
      industries: ['Accounting', 'Finance'],
      category: 'Business',
      url: 'https://bapuoa.org',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 10 * day).toISOString(),
      benefits: ['Big Four networking', 'Honour society membership', 'Community service'],
    },
    {
      id: 'club_uoa_ieee',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_ieee',
      title: 'IEEE UoA Student Branch',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/ieee.uoa',
      description: 'The University of Auckland branch of the world\'s largest technical professional organisation. IEEE UoA runs technical workshops on embedded systems, signal processing, and power engineering, along with industry site visits and paper-reading groups.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['electrical-engineering', 'electronics', 'ieee', 'workshops', 'technical'],
      skills: ['electrical-engineering', 'signal-processing', 'technical-writing'],
      industries: ['Engineering', 'Electronics', 'Technology'],
      category: 'Engineering',
      url: 'https://linktr.ee/ieee.uoa',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 11 * day).toISOString(),
      benefits: ['IEEE membership benefits', 'Technical workshops', 'Industry site visits'],
    },
    {
      id: 'club_uoa_besa',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_besa',
      title: 'Biomedical Engineering & Engineering Science Student Association (BESA)',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/besa_uoa',
      description: 'Represents biomedical engineering and engineering science students at UoA. BESA organises study sessions, industry panels with medical device companies, lab showcases, and social events to build a tight-knit engineering community.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['biomedical-engineering', 'engineering-science', 'medical-devices', 'academic'],
      skills: ['engineering', 'research', 'teamwork'],
      industries: ['Biomedical Engineering', 'Healthcare', 'Engineering'],
      category: 'Engineering',
      url: 'https://linktr.ee/besa_uoa',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      benefits: ['Industry panels', 'Lab showcases', 'Study sessions'],
    },
    {
      id: 'club_uoa_hta',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_hta',
      title: 'Healthcare Technology Association (HTA NZ)',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/htanz',
      description: 'Bridges the gap between healthcare and technology. HTA runs hackathons focused on health-tech solutions, hosts speakers from digital health startups, and connects students interested in health informatics and medtech innovation.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      isRemote: true,
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['health-tech', 'medtech', 'innovation', 'hackathons', 'digital-health'],
      skills: ['health-informatics', 'programming', 'innovation'],
      industries: ['Healthcare', 'Technology', 'Startups'],
      category: 'Health & Medicine',
      url: 'https://linktr.ee/htanz',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 9 * day).toISOString(),
      benefits: ['Health-tech hackathons', 'Startup speaker events', 'Interdisciplinary networking'],
    },
    {
      id: 'club_uoa_cesa',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_cesa',
      title: 'Civil & Structural Engineering Students\' Association (CESA)',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/uoacesa',
      description: 'The student association for civil and structural engineering at UoA. CESA organises site visits to major Auckland construction projects, industry networking with engineering firms, technical seminars, and the annual CESA ball.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['civil-engineering', 'structural-engineering', 'construction', 'careers'],
      skills: ['engineering', 'project-management', 'networking'],
      industries: ['Civil Engineering', 'Construction', 'Infrastructure'],
      category: 'Engineering',
      url: 'https://linktr.ee/uoacesa',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 12 * day).toISOString(),
      benefits: ['Construction site visits', 'Industry networking', 'Annual ball'],
    },
    {
      id: 'club_uoa_debating',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_debsoc',
      title: 'University of Auckland Debating Society',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/uoadebsoc',
      description: 'One of NZ\'s most successful debating societies. Trains members in British Parliamentary and Australs styles, competes at national and international tournaments, and hosts weekly practice sessions open to all skill levels.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['debating', 'public-speaking', 'critical-thinking', 'competitions'],
      skills: ['public-speaking', 'critical-thinking', 'argumentation', 'research'],
      industries: ['Law', 'Politics', 'Communications'],
      category: 'Public Speaking',
      url: 'https://linktr.ee/uoadebsoc',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 1 * day).toISOString(),
      benefits: ['Tournament travel', 'Weekly practice', 'Public speaking skills'],
    },
    {
      id: 'club_uoa_tedx',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_tedx',
      title: 'TEDxUOA',
      organization: 'University of Auckland',
      organizationUrl: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      description: 'The independently organised TEDx event at the University of Auckland. TEDxUOA curates talks from inspiring speakers across science, technology, design, and social innovation, and recruits student volunteers for event production.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['tedx', 'public-speaking', 'ideas', 'events', 'volunteering'],
      skills: ['event-management', 'communication', 'leadership'],
      industries: ['Media', 'Events', 'Communications'],
      category: 'Public Speaking',
      url: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 7 * day).toISOString(),
      benefits: ['Event production experience', 'Speaker networking', 'CV-worthy volunteering'],
    },
    {
      id: 'club_uoa_aeronautics',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_uac',
      title: 'University of Auckland Aeronautics Club',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/uacuoa',
      description: 'Designs, builds, and flies aircraft and drones. The club enters national UAV competitions, runs workshops on aerodynamics and CAD, and provides hands-on experience with composites, electronics, and flight testing.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['aeronautics', 'drones', 'uav', 'engineering', 'flight'],
      skills: ['cad', 'aerodynamics', 'electronics', 'engineering'],
      industries: ['Aerospace', 'Engineering', 'Defence'],
      category: 'Engineering',
      url: 'https://linktr.ee/uacuoa',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 14 * day).toISOString(),
      benefits: ['UAV competitions', 'Hands-on building', 'CAD workshops'],
    },
    {
      id: 'club_uoa_rocketry',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_rocketry',
      title: 'University of Auckland Rocketry Club',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/uoarocketry',
      description: 'Designs and launches high-powered rockets, competing in events like the Australasian Universities Rocketry Competition. Members gain experience in propulsion, avionics, structures, and recovery systems.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['rocketry', 'aerospace', 'engineering', 'propulsion', 'competition'],
      skills: ['engineering', 'propulsion', 'avionics', 'project-management'],
      industries: ['Aerospace', 'Engineering'],
      category: 'Engineering',
      url: 'https://linktr.ee/uoarocketry',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 13 * day).toISOString(),
      benefits: ['Rocket launches', 'Competition travel', 'Hands-on engineering'],
    },
    {
      id: 'club_uoa_space_hub',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_spacehub',
      title: 'Space Hub Auckland',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/spacehubauckland',
      description: 'Connects students passionate about the space industry — from satellite engineering to space policy. Hosts talks with Rocket Lab engineers, space law seminars, and collaborative projects with NZ\'s growing space sector.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      isRemote: true,
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['space', 'aerospace', 'satellite', 'space-policy', 'rocket-lab'],
      skills: ['engineering', 'research', 'policy-analysis'],
      industries: ['Aerospace', 'Space', 'Defence'],
      category: 'Engineering',
      url: 'https://linktr.ee/spacehubauckland',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      benefits: ['Industry speaker events', 'Space sector networking', 'Collaborative projects'],
    },
    {
      id: 'club_uoa_marine_science',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_marinesci',
      title: 'University of Auckland Marine Science Society',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/uoamarinesociety',
      description: 'For students passionate about marine biology, oceanography, and ocean conservation. Organises beach clean-ups, snorkelling trips, marine research talks, and connects students with marine science career pathways in New Zealand.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['marine-science', 'biology', 'conservation', 'oceanography', 'environment'],
      skills: ['research', 'fieldwork', 'conservation'],
      industries: ['Marine Science', 'Environmental Science', 'Research'],
      category: 'Science',
      url: 'https://linktr.ee/uoamarinesociety',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 10 * day).toISOString(),
      benefits: ['Field trips', 'Beach clean-ups', 'Research talks'],
    },
    {
      id: 'club_uoa_public_policy',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_ppc',
      title: 'Public Policy Club',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/publicpolicyclub',
      description: 'Fosters discussion and understanding of public policy issues in New Zealand and beyond. Hosts policy workshops, guest lectures from politicians and public servants, and simulated select committee hearings.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['public-policy', 'politics', 'government', 'debate', 'social-issues'],
      skills: ['policy-analysis', 'critical-thinking', 'public-speaking', 'research'],
      industries: ['Government', 'Policy', 'Public Sector'],
      category: 'Politics & Policy',
      url: 'https://linktr.ee/publicpolicyclub',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      benefits: ['Policy workshops', 'Guest lectures', 'Government networking'],
    },

    // ── UoA Causes ─────────────────────────────────────────────────────

    {
      id: 'club_uoa_esd',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_esd',
      title: 'Engineering for Sustainable Development (ESD)',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/esduoa',
      description: 'Applies engineering skills to sustainability challenges. ESD runs projects on renewable energy, waste reduction, and sustainable design, partnering with community organisations to deliver real impact.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['sustainability', 'engineering', 'renewable-energy', 'social-impact', 'environment'],
      skills: ['engineering', 'sustainability', 'project-management'],
      industries: ['Environmental Engineering', 'Sustainability', 'Energy'],
      category: 'Sustainability',
      url: 'https://linktr.ee/esduoa',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 8 * day).toISOString(),
      benefits: ['Sustainability projects', 'Community partnerships', 'Engineering for good'],
    },
    {
      id: 'club_uoa_equal_justice',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_ejp',
      title: 'Equal Justice Project',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/equaljusticeproject',
      description: 'A student-run initiative promoting access to justice and human rights. Members publish legal research, run community legal education workshops, and advocate for policy reform on issues like housing, immigration, and criminal justice.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      isRemote: true,
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['social-justice', 'law', 'human-rights', 'advocacy', 'community'],
      skills: ['legal-research', 'writing', 'advocacy', 'public-speaking'],
      industries: ['Law', 'Non-profit', 'Public Sector'],
      category: 'Law',
      url: 'https://linktr.ee/equaljusticeproject',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 5 * day).toISOString(),
      benefits: ['Published research', 'Community impact', 'Legal education experience'],
    },
    {
      id: 'club_uoa_sva',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_sva',
      title: 'University of Auckland Student Volunteer Army',
      organization: 'University of Auckland',
      organizationUrl: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      description: 'Part of the national SVA movement born from the Christchurch earthquakes. Mobilises UoA students for community volunteering — from neighbourhood clean-ups to tutoring programmes and disaster response preparedness.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['volunteering', 'community', 'social-impact', 'leadership', 'service'],
      skills: ['leadership', 'teamwork', 'community-engagement'],
      industries: ['Non-profit', 'Community Services'],
      category: 'Volunteering',
      url: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 2 * day).toISOString(),
      benefits: ['Volunteering hours', 'Community impact', 'Leadership experience'],
    },
    {
      id: 'club_uoa_unicef',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_unicef',
      title: 'Auckland Students UNICEF',
      organization: 'University of Auckland',
      organizationUrl: 'https://hopp.bio/aucklandstudentsunicef',
      description: 'Raises awareness and funds for UNICEF\'s global programmes supporting children\'s rights, education, and health. Runs fundraising campaigns, advocacy events, and educational seminars on international development issues.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['unicef', 'charity', 'international-development', 'fundraising', 'advocacy'],
      skills: ['fundraising', 'event-management', 'advocacy'],
      industries: ['Non-profit', 'International Development'],
      category: 'Volunteering',
      url: 'https://hopp.bio/aucklandstudentsunicef',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 11 * day).toISOString(),
      benefits: ['Fundraising experience', 'Global awareness', 'Advocacy skills'],
    },
    {
      id: 'club_uoa_sustainable_future',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_sfc',
      title: 'Sustainable Future Collective',
      organization: 'University of Auckland',
      organizationUrl: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      description: 'An interdisciplinary collective tackling climate change and sustainability on campus and beyond. Hosts zero-waste workshops, climate film screenings, panel discussions with environmental scientists, and campus greening projects.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['sustainability', 'climate', 'environment', 'zero-waste', 'advocacy'],
      skills: ['sustainability', 'advocacy', 'project-management'],
      industries: ['Environmental Science', 'Sustainability', 'Non-profit'],
      category: 'Sustainability',
      url: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 14 * day).toISOString(),
      benefits: ['Sustainability workshops', 'Climate advocacy', 'Campus impact projects'],
    },

    // ── UoA Special Interest ───────────────────────────────────────────

    {
      id: 'club_uoa_maker',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_makeuoa',
      title: 'Auckland University Maker Club (MakeUoA)',
      organization: 'University of Auckland',
      organizationUrl: 'https://makeuoa.nz',
      description: 'The maker and hardware hacking community at UoA. Runs the annual CREATE hackathon, weekly maker nights with 3D printers, laser cutters, and soldering stations, plus workshops on electronics, CAD, and rapid prototyping.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['maker', 'hardware', '3d-printing', 'hackathon', 'electronics', 'prototyping'],
      skills: ['prototyping', 'electronics', 'cad', '3d-printing'],
      industries: ['Engineering', 'Technology', 'Manufacturing'],
      category: 'Technology',
      url: 'https://makeuoa.nz',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      benefits: ['Makerspace access', 'CREATE hackathon', 'Hardware workshops'],
    },
    {
      id: 'club_uoa_chess',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_auca',
      title: 'Auckland University Chess Association (AUCA)',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/AUCA2026',
      description: 'For chess enthusiasts of all levels. AUCA holds weekly club nights with casual and rated games, enters teams in inter-university chess tournaments, and runs beginner workshops to grow the chess community on campus.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['chess', 'strategy', 'competition', 'games', 'social'],
      skills: ['strategic-thinking', 'problem-solving'],
      industries: ['Recreation'],
      category: 'Games & Recreation',
      url: 'https://linktr.ee/AUCA2026',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 9 * day).toISOString(),
      benefits: ['Weekly club nights', 'Tournament entry', 'Beginner workshops'],
    },
    {
      id: 'club_uoa_game_dev',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_gdg_games',
      title: 'The Game Developer Guild',
      organization: 'University of Auckland',
      organizationUrl: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      description: 'A community for aspiring game developers at UoA. Members collaborate on game jams, learn Unity and Unreal Engine, share works-in-progress, and hear from NZ game studio developers about career paths in the industry.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      isRemote: true,
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['game-development', 'unity', 'unreal-engine', 'programming', 'game-design'],
      skills: ['game-development', 'programming', 'design', 'teamwork'],
      industries: ['Gaming', 'Technology', 'Entertainment'],
      category: 'Technology',
      url: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 7 * day).toISOString(),
      benefits: ['Game jams', 'Engine workshops', 'Industry talks'],
    },
    {
      id: 'club_uoa_esports',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_esports',
      title: 'University of Auckland Esports Club',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/AucklandUniEsportsClub',
      description: 'Competitive and casual gaming at UoA. Fields teams in Valorant, League of Legends, CS2, and more for inter-university leagues. Also hosts LAN events, watch parties, and casual gaming nights open to everyone.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      isRemote: true,
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['esports', 'gaming', 'competition', 'valorant', 'league-of-legends'],
      skills: ['teamwork', 'communication', 'strategy'],
      industries: ['Esports', 'Entertainment'],
      category: 'Games & Recreation',
      url: 'https://linktr.ee/AucklandUniEsportsClub',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 1 * day).toISOString(),
      benefits: ['Competitive teams', 'LAN events', 'Gaming community'],
    },
    {
      id: 'club_uoa_photography',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_photosoc',
      title: 'UoA Photography Society',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/UOAPhotoSociety',
      description: 'A creative community for photographers of all skill levels. Hosts photowalks around Auckland, editing workshops using Lightroom and Photoshop, themed photo challenges, and exhibitions showcasing student work.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['photography', 'creative', 'art', 'editing', 'community'],
      skills: ['photography', 'photo-editing', 'creativity'],
      industries: ['Creative Arts', 'Media'],
      category: 'Creative Arts',
      url: 'https://linktr.ee/UOAPhotoSociety',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 5 * day).toISOString(),
      benefits: ['Photowalks', 'Editing workshops', 'Exhibition opportunities'],
    },
    {
      id: 'club_uoa_vr',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_vr',
      title: 'UoA VR Club',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/uoa.vr',
      description: 'Explores virtual reality, augmented reality, and mixed reality technologies. Members get hands-on time with VR headsets, develop XR applications in Unity, and discuss the future of immersive technology across gaming, education, and healthcare.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['virtual-reality', 'augmented-reality', 'xr', 'unity', 'immersive-tech'],
      skills: ['vr-development', 'unity', '3d-modelling', 'programming'],
      industries: ['Technology', 'Gaming', 'Education'],
      category: 'Technology',
      url: 'https://linktr.ee/uoa.vr',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 12 * day).toISOString(),
      benefits: ['VR headset access', 'XR development workshops', 'Demo nights'],
    },
    {
      id: 'club_uoa_dance',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_auda',
      title: 'Auckland University Dance Association (AUDA)',
      organization: 'University of Auckland',
      organizationUrl: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      description: 'One of UoA\'s largest social clubs bringing together dancers of all styles and levels. Offers weekly classes in hip-hop, K-pop, contemporary, and Latin dance, plus performs at university events and enters regional competitions.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['dance', 'hip-hop', 'kpop', 'contemporary', 'performing-arts'],
      skills: ['dance', 'performance', 'teamwork'],
      industries: ['Performing Arts', 'Entertainment'],
      category: 'Performing Arts',
      url: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      benefits: ['Weekly dance classes', 'Performance opportunities', 'Dance competitions'],
    },
    {
      id: 'club_uoa_fsae',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_fsae',
      title: 'Formula SAE — University of Auckland',
      organization: 'University of Auckland',
      organizationUrl: 'https://fsae.co.nz',
      description: 'Designs and builds a formula-style race car from scratch each year to compete in the Australasian Formula SAE competition. An intense, hands-on engineering project spanning mechanical design, electronics, manufacturing, and business planning.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['formula-sae', 'motorsport', 'engineering', 'manufacturing', 'design'],
      skills: ['mechanical-engineering', 'cad', 'manufacturing', 'project-management'],
      industries: ['Automotive', 'Engineering', 'Motorsport'],
      category: 'Engineering',
      url: 'https://fsae.co.nz',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 15 * day).toISOString(),
      benefits: ['Race car build experience', 'Competition travel', 'Industry sponsors'],
    },
    {
      id: 'club_uoa_rpg',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_arpg',
      title: 'Auckland Roleplaying Guild',
      organization: 'University of Auckland',
      organizationUrl: 'https://aucklandrpg.nz',
      description: 'Auckland\'s premier tabletop roleplaying community based at UoA. Runs weekly sessions of Dungeons & Dragons, Pathfinder, Call of Cthulhu, and more, plus one-shot events and game-mastering workshops for beginners.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['tabletop-rpg', 'dungeons-and-dragons', 'gaming', 'social', 'creative-writing'],
      skills: ['storytelling', 'creativity', 'teamwork'],
      industries: ['Recreation', 'Entertainment'],
      category: 'Games & Recreation',
      url: 'https://aucklandrpg.nz',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      benefits: ['Weekly game sessions', 'GM workshops', 'Social community'],
    },

    // ── UoA Sports ─────────────────────────────────────────────────────

    {
      id: 'club_uoa_tramping',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_autc',
      title: 'AU Tramping Club (AUTC)',
      organization: 'University of Auckland',
      organizationUrl: 'https://autc.org.nz',
      description: 'One of NZ\'s oldest and most active tramping clubs. AUTC organises weekend hikes, multi-day backcountry tramps, mountaineering trips, and maintains a gear library so students can experience the outdoors without expensive kit.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['tramping', 'hiking', 'outdoors', 'adventure', 'mountaineering'],
      skills: ['outdoor-skills', 'navigation', 'teamwork', 'fitness'],
      industries: ['Recreation', 'Tourism'],
      category: 'Sports & Outdoors',
      url: 'https://autc.org.nz',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 2 * day).toISOString(),
      benefits: ['Gear library', 'Weekend trips', 'Multi-day tramps'],
    },
    {
      id: 'club_uoa_boat',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_aubc',
      title: 'Auckland University Boat Club (AUBC)',
      organization: 'University of Auckland',
      organizationUrl: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      description: 'UoA\'s competitive rowing club training out of the Waitematā Harbour. Offers learn-to-row programmes for beginners and competitive crews that race at regattas around New Zealand, including the Maadi Cup and NZ University Championships.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['rowing', 'sport', 'fitness', 'competition', 'water-sport'],
      skills: ['fitness', 'teamwork', 'discipline'],
      industries: ['Sport'],
      category: 'Sports & Outdoors',
      url: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 10 * day).toISOString(),
      benefits: ['Learn-to-row programme', 'Regatta competition', 'Fitness community'],
    },
    {
      id: 'club_uoa_fencing',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_aufc',
      title: 'Auckland University Fencing Club',
      organization: 'University of Auckland',
      organizationUrl: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      description: 'Learn the art of fencing — foil, épée, and sabre — regardless of experience. The club provides all equipment, runs beginner and advanced training sessions, and competes in inter-university and national fencing competitions.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['fencing', 'sport', 'martial-arts', 'competition', 'fitness'],
      skills: ['fencing', 'discipline', 'fitness'],
      industries: ['Sport'],
      category: 'Sports & Outdoors',
      url: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 13 * day).toISOString(),
      benefits: ['Equipment provided', 'Beginner training', 'Competition opportunities'],
    },
    {
      id: 'club_uoa_volleyball',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_uoavc',
      title: 'University of Auckland Volleyball Club (UOAVC)',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/UOAVC',
      description: 'UoA\'s largest volleyball community with competitive and social divisions. Enters teams in Auckland Volleyball Association leagues and hosts inter-faculty tournaments, social games, and skills clinics for all levels.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['volleyball', 'sport', 'fitness', 'competition', 'social'],
      skills: ['teamwork', 'fitness', 'communication'],
      industries: ['Sport'],
      category: 'Sports & Outdoors',
      url: 'https://linktr.ee/UOAVC',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      benefits: ['League competition', 'Social games', 'Skills clinics'],
    },
    {
      id: 'club_uoa_football',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_uoafc',
      title: 'UoA Football Club',
      organization: 'University of Auckland',
      organizationUrl: 'https://linktr.ee/uoafc',
      description: 'The biggest football (soccer) club on campus, fielding men\'s and women\'s teams in Auckland Football Federation leagues. Also runs social five-a-side competitions and futsal nights for casual players.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['football', 'soccer', 'sport', 'fitness', 'competition'],
      skills: ['teamwork', 'fitness', 'communication'],
      industries: ['Sport'],
      category: 'Sports & Outdoors',
      url: 'https://linktr.ee/uoafc',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 8 * day).toISOString(),
      benefits: ['League football', 'Social futsal', 'Fitness community'],
    },
    {
      id: 'club_uoa_basketball',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_basketball',
      title: 'University of Auckland Basketball Club',
      organization: 'University of Auckland',
      organizationUrl: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      description: 'Competitive and social basketball for UoA students. Enters teams in Auckland Basketball Association leagues and university tournaments, with regular training sessions, pick-up games, and inter-faculty competitions.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['basketball', 'sport', 'fitness', 'competition', 'social'],
      skills: ['teamwork', 'fitness', 'communication'],
      industries: ['Sport'],
      category: 'Sports & Outdoors',
      url: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 11 * day).toISOString(),
      benefits: ['League competition', 'Pick-up games', 'Regular training'],
    },
    {
      id: 'club_uoa_snowsports',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_snowsports',
      title: 'UoA Snowsports Club',
      organization: 'University of Auckland',
      organizationUrl: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      description: 'Skiing and snowboarding community at UoA. Organises group trips to Ruapehu and South Island ski fields during winter, hosts après-ski socials, and negotiates discounted season passes and gear for members.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['skiing', 'snowboarding', 'winter-sports', 'adventure', 'social'],
      skills: ['fitness', 'outdoor-skills'],
      industries: ['Sport', 'Tourism'],
      category: 'Sports & Outdoors',
      url: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 15 * day).toISOString(),
      benefits: ['Discounted ski trips', 'Season pass deals', 'Social events'],
    },
    {
      id: 'club_uoa_run',
      type: 'club',
      source: 'curated',
      sourceId: 'uoa_runclub',
      title: 'UoA Run Club',
      organization: 'University of Auckland',
      organizationUrl: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      description: 'A welcoming running community for all paces and distances. Hosts weekly group runs around Auckland Domain and the waterfront, enters teams in fun runs and half marathons, and organises social brunch runs on weekends.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['running', 'fitness', 'sport', 'social', 'health'],
      skills: ['fitness', 'discipline'],
      industries: ['Sport', 'Health & Wellness'],
      category: 'Sports & Outdoors',
      url: 'https://www.auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      applicationType: 'none',
      status: 'active',
      createdAt: new Date(now - 1 * day).toISOString(),
      benefits: ['Weekly group runs', 'Race team entries', 'Social running events'],
    },

    // ── AUT Clubs ──────────────────────────────────────────────────────

    {
      id: 'club_aut_accounting',
      type: 'club',
      source: 'curated',
      sourceId: 'aut_aaa',
      title: 'AUT Accounting Association',
      organization: 'AUT Students\' Association (AUTSA)',
      organizationUrl: 'https://autsa.org.nz/clubs',
      description: 'Supports AUT accounting students with career preparation, employer networking nights with Big Four and mid-tier firms, CA/CPA exam study groups, and professional development workshops.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['accounting', 'careers', 'networking', 'aut', 'professional'],
      skills: ['accounting', 'networking', 'professional-development'],
      industries: ['Accounting', 'Finance'],
      category: 'Business',
      url: 'https://autsa.org.nz/clubs',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 9 * day).toISOString(),
      benefits: ['Employer networking', 'Study groups', 'Professional workshops'],
    },
    {
      id: 'club_aut_investment',
      type: 'club',
      source: 'curated',
      sourceId: 'aut_invest',
      title: 'AUT Investment Club',
      organization: 'AUT Students\' Association (AUTSA)',
      organizationUrl: 'https://autsa.org.nz/clubs',
      description: 'Educates AUT students about investing, financial markets, and wealth management. Runs stock-picking competitions, portfolio simulations, guest lectures from fund managers, and workshops on personal finance.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['investing', 'finance', 'stock-market', 'aut', 'wealth-management'],
      skills: ['financial-analysis', 'investing', 'critical-thinking'],
      industries: ['Finance', 'Investment Banking'],
      category: 'Business',
      url: 'https://autsa.org.nz/clubs',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      benefits: ['Stock-picking competitions', 'Fund manager talks', 'Financial literacy'],
    },
    {
      id: 'club_aut_gaming',
      type: 'club',
      source: 'curated',
      sourceId: 'aut_gaming',
      title: 'AUT Gaming Society',
      organization: 'AUT Students\' Association (AUTSA)',
      organizationUrl: 'https://autsa.org.nz/clubs',
      description: 'AUT\'s home for gamers — casual and competitive. Hosts regular LAN parties, console tournaments, board game nights, and enters esports teams in inter-university leagues across multiple titles.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      isRemote: true,
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['gaming', 'esports', 'aut', 'social', 'board-games'],
      skills: ['teamwork', 'communication', 'strategy'],
      industries: ['Esports', 'Entertainment'],
      category: 'Games & Recreation',
      url: 'https://autsa.org.nz/clubs',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 2 * day).toISOString(),
      benefits: ['LAN parties', 'Esports teams', 'Board game nights'],
    },
    {
      id: 'club_aut_stem_women',
      type: 'club',
      source: 'curated',
      sourceId: 'aut_stemw',
      title: 'AUT STEM Women',
      organization: 'AUT Students\' Association (AUTSA)',
      organizationUrl: 'https://autsa.org.nz/clubs',
      description: 'Empowers women and non-binary students in science, technology, engineering, and maths at AUT. Provides mentorship, industry panels with women in STEM leadership, scholarship information, and a supportive peer network.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['women-in-stem', 'diversity', 'mentorship', 'aut', 'empowerment'],
      skills: ['leadership', 'networking', 'mentoring'],
      industries: ['Technology', 'Science', 'Engineering'],
      category: 'Science',
      url: 'https://autsa.org.nz/clubs',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 7 * day).toISOString(),
      benefits: ['Mentorship programme', 'Industry panels', 'Peer support network'],
    },
    {
      id: 'club_aut_science',
      type: 'club',
      source: 'curated',
      sourceId: 'aut_sciassoc',
      title: 'AUT Science Association',
      organization: 'AUT Students\' Association (AUTSA)',
      organizationUrl: 'https://autsa.org.nz/clubs',
      description: 'Represents science students across all disciplines at AUT. Organises lab tours, guest lectures from researchers, science quizzes, study groups, and advocates for student interests within the Faculty of Health and Environmental Sciences.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['science', 'research', 'academic', 'aut', 'lab'],
      skills: ['research', 'scientific-method', 'teamwork'],
      industries: ['Science', 'Research', 'Healthcare'],
      category: 'Science',
      url: 'https://autsa.org.nz/clubs',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 14 * day).toISOString(),
      benefits: ['Lab tours', 'Research talks', 'Study groups'],
    },
    {
      id: 'club_aut_cybersecurity',
      type: 'club',
      source: 'curated',
      sourceId: 'aut_cyber',
      title: 'AUT Cyber Security & Intelligence',
      organization: 'AUT Students\' Association (AUTSA)',
      organizationUrl: 'https://autsa.org.nz/clubs',
      description: 'For students interested in cybersecurity, ethical hacking, and intelligence analysis. Hosts capture-the-flag (CTF) competitions, penetration testing workshops, guest speakers from NZ\'s security sector, and study groups for security certifications.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      isRemote: true,
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['cybersecurity', 'ethical-hacking', 'ctf', 'aut', 'intelligence'],
      skills: ['cybersecurity', 'penetration-testing', 'networking', 'problem-solving'],
      industries: ['Cybersecurity', 'Technology', 'Defence'],
      category: 'Technology',
      url: 'https://autsa.org.nz/clubs',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      benefits: ['CTF competitions', 'Pen-testing workshops', 'Security sector networking'],
    },
    {
      id: 'club_aut_law',
      type: 'club',
      source: 'curated',
      sourceId: 'aut_autlss',
      title: 'AUT Law Students\' Society (AUTLSS)',
      organization: 'AUT Students\' Association (AUTSA)',
      organizationUrl: 'https://autsa.org.nz/clubs',
      description: 'Represents law students at AUT, providing academic support, networking evenings with law firms, mooting competitions, and career guidance for students navigating the NZ legal profession. Open to all AUT law students.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['law', 'careers', 'networking', 'mooting', 'aut'],
      skills: ['legal-skills', 'public-speaking', 'networking'],
      industries: ['Law'],
      category: 'Law',
      url: 'https://autsa.org.nz/clubs',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 12 * day).toISOString(),
      benefits: ['Law firm networking', 'Mooting competitions', 'Career guidance'],
    },
    {
      id: 'club_aut_performing_arts',
      type: 'club',
      source: 'curated',
      sourceId: 'aut_performingarts',
      title: 'AUT Performing Arts',
      organization: 'AUT Students\' Association (AUTSA)',
      organizationUrl: 'https://autsa.org.nz/clubs',
      description: 'A creative hub for AUT students interested in theatre, music, and performance. Produces student-led shows, open mic nights, improv workshops, and collaborative performances that showcase diverse talent across the university.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['performing-arts', 'theatre', 'music', 'aut', 'creative'],
      skills: ['performance', 'creativity', 'teamwork', 'public-speaking'],
      industries: ['Performing Arts', 'Entertainment'],
      category: 'Performing Arts',
      url: 'https://autsa.org.nz/clubs',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 5 * day).toISOString(),
      benefits: ['Student shows', 'Open mic nights', 'Performance workshops'],
    },
    {
      id: 'club_aut_film',
      type: 'club',
      source: 'curated',
      sourceId: 'aut_film',
      title: 'AUT Film Club',
      organization: 'AUT Students\' Association (AUTSA)',
      organizationUrl: 'https://autsa.org.nz/clubs',
      description: 'For film lovers and aspiring filmmakers at AUT. Hosts movie screenings and discussions, short film challenges, editing workshops, and collaborates on student film projects using AUT\'s production facilities.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['film', 'cinema', 'filmmaking', 'aut', 'creative'],
      skills: ['filmmaking', 'video-editing', 'storytelling', 'creativity'],
      industries: ['Film', 'Media', 'Entertainment'],
      category: 'Creative Arts',
      url: 'https://autsa.org.nz/clubs',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 8 * day).toISOString(),
      benefits: ['Film screenings', 'Short film challenges', 'Production facilities access'],
    },
    {
      id: 'club_aut_ocha_no_jikan',
      type: 'club',
      source: 'curated',
      sourceId: 'aut_ocha',
      title: 'Ocha No Jikan — AUT Japanese Culture Club',
      organization: 'AUT Students\' Association (AUTSA)',
      organizationUrl: 'https://autsa.org.nz/clubs',
      description: 'Celebrates Japanese culture through tea ceremonies, calligraphy workshops, anime screenings, language exchange meetups, and Japanese cooking classes. A welcoming space for anyone interested in Japanese culture, whether a beginner or fluent speaker.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['japanese-culture', 'language-exchange', 'anime', 'cultural', 'aut'],
      skills: ['cross-cultural-communication', 'language-skills'],
      industries: ['Culture', 'Education'],
      category: 'Culture & Language',
      url: 'https://autsa.org.nz/clubs',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 10 * day).toISOString(),
      benefits: ['Tea ceremonies', 'Language exchange', 'Cultural workshops'],
    },
  ];
}

export const clubsConnector: OpportunityConnector = {
  name: 'clubs',
  supportedTypes: ['club'],
  async fetch(config): Promise<ConnectorResult> {
    const errors: string[] = [];
    let opportunities: Opportunity[] = [];

    try {
      const live = await fetchAUTSAClubs();
      opportunities.push(...live);
      console.log(`[ClubsConnector] Scraped ${live.length} clubs from AUTSA`);
    } catch (err) {
      errors.push(`AUTSA: ${String(err)}`);
    }

    opportunities.push(...getCuratedClubs());

    if (config.maxResults) {
      opportunities = opportunities.slice(0, config.maxResults);
    }

    return {
      opportunities,
      source: 'clubs',
      fetchedAt: new Date().toISOString(),
      stats: { fetched: opportunities.length, validated: opportunities.length, errors },
    };
  },
};
