import { Opportunity } from '@/types/opportunities';
import { OpportunityConnector, ConnectorConfig, ConnectorResult } from './types';
import * as cheerio from 'cheerio';

async function fetchDevpostHackathons(): Promise<Opportunity[]> {
  try {
    const res = await fetch('https://devpost.com/hackathons?status=open&order_by=deadline', {
      headers: { 'User-Agent': 'Gradual-App/2.0', Accept: 'text/html' },
    });
    if (!res.ok) return [];
    const html = await res.text();
    const $ = cheerio.load(html);
    const hackathons: Opportunity[] = [];

    $('.hackathon-tile, [data-hackathon-tile], .hackathons-container a[href*="devpost.com"]').each((_i, el) => {
      const $el = $(el);
      const title = $el.find('h2, h3, .title, .hackathon-title').first().text().trim();
      const link = $el.attr('href') || $el.find('a').first().attr('href') || '';
      const org = $el.find('.host, .organizer, .organization').first().text().trim();
      const desc = $el.find('.tagline, .description, p').first().text().trim();
      const prize = $el.find('.prize, .prizes').first().text().trim();

      if (!title || !link) return;
      const fullUrl = link.startsWith('http') ? link : `https://devpost.com${link}`;

      hackathons.push({
        id: `devpost_${link.replace(/[^a-z0-9]/gi, '_').slice(0, 60)}`,
        type: 'competition',
        source: 'devpost',
        sourceId: link,
        sourceUrl: fullUrl,
        title,
        organization: org || 'DevPost Hackathon',
        description: desc || title,
        summary: prize ? `Prize pool: ${prize}` : undefined,
        location: 'Online',
        locationType: 'remote',
        isRemote: true,
        country: 'International',
        tags: ['hackathon', 'competition', 'coding', 'innovation'],
        skills: ['programming', 'teamwork', 'innovation'],
        category: 'Competitions',
        url: fullUrl,
        applicationType: 'external',
        status: 'active',
        createdAt: new Date().toISOString(),
        compensation: prize ? { type: 'paid', description: prize } : undefined,
      });
    });
    return hackathons.slice(0, 15);
  } catch (err) {
    console.error('[CompetitionsConnector] DevPost fetch failed:', err);
    return [];
  }
}

function getCuratedCompetitions(): Opportunity[] {
  const now = Date.now();
  const day = 24 * 60 * 60 * 1000;
  return [
    {
      id: 'comp_ai_hackathon_nz',
      type: 'competition',
      source: 'curated',
      sourceId: 'ai_hackathon_nz_2026',
      title: 'AI Hackathon NZ 2026',
      organization: 'AI Hackathon Aotearoa',
      organizationUrl: 'https://aihackathon.nz/',
      description: '48-hour hackathons across NZ — Wellington, Waikato, Christchurch, Auckland (two venues), and Dunedin from 3-10 August 2026. Tackle real-world challenges including food insecurity, digital accessibility, workforce upskilling, and indigenous environmental custodianship. Winners pitch at the Aotearoa AI Summit on 18 September.',
      location: 'Multiple cities, New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['hackathon', 'ai', 'machine-learning', 'coding', 'innovation', 'competition'],
      categoryTags: ['hackathon', 'ai'],
      skills: ['programming', 'ai', 'machine-learning', 'teamwork', 'rapid-prototyping'],
      industries: ['Technology', 'AI'],
      category: 'Competitions',
      url: 'https://aihackathon.nz/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 5 * day).toISOString(),
      startDate: new Date(now + 120 * day).toISOString(),
      endDate: new Date(now + 127 * day).toISOString(),
      dates: {
        startDate: new Date(now + 120 * day).toISOString(),
        endDate: new Date(now + 127 * day).toISOString(),
      },
      benefits: ['Prizes', 'Pitch at AI Summit', 'Industry mentorship', 'Nationwide network'],
    },
    {
      id: 'comp_uoa_case_baker_tilly',
      type: 'competition',
      source: 'curated',
      sourceId: 'uoa_bt_case_2026',
      title: 'Baker Tilly First Timers\' & Open Case Competition',
      organization: 'University of Auckland Case Club',
      organizationUrl: 'https://uoacaseclub.co.nz',
      description: 'Analyse a real business case and present strategy recommendations to industry judges. Teams develop communication, analytical thinking, and teamwork skills. Open to all UoA students — no prior case experience needed for First Timers\' track.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['case-competition', 'business', 'strategy', 'consulting', 'presentation'],
      skills: ['business-analysis', 'presentation', 'strategy', 'teamwork'],
      industries: ['Consulting', 'Business'],
      category: 'Competitions',
      url: 'https://uoacaseclub.co.nz/competitions-2026',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      deadline: new Date(now + 30 * day).toISOString(),
      dates: { deadline: new Date(now + 30 * day).toISOString() },
      benefits: ['Industry judges', 'Consulting exposure', 'Networking'],
    },
    {
      id: 'comp_uoa_zuru_case',
      type: 'competition',
      source: 'curated',
      sourceId: 'uoa_zuru_2026',
      title: 'ZURU Case Competition',
      organization: 'University of Auckland Case Club',
      organizationUrl: 'https://uoacaseclub.co.nz',
      description: 'In teams of 4, generate an innovative strategy for ZURU Edge — one of the fastest-growing FMCG companies in the world. Learn what it takes to succeed in the consumer goods industry and apply creative thinking skills.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['case-competition', 'fmcg', 'strategy', 'innovation', 'consumer-goods'],
      skills: ['strategy', 'creative-thinking', 'teamwork', 'presentation'],
      industries: ['FMCG', 'Consumer Goods'],
      category: 'Competitions',
      url: 'https://uoacaseclub.co.nz/competitions-2026',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      deadline: new Date(now + 35 * day).toISOString(),
      dates: { deadline: new Date(now + 35 * day).toISOString() },
    },
    {
      id: 'comp_uc_disrupt',
      type: 'competition',
      source: 'curated',
      sourceId: 'uc_disrupt_2026',
      title: 'UC Breaking Ground Disrupt Challenge 2026',
      organization: 'University of Canterbury Centre for Entrepreneurship',
      organizationUrl: 'https://www.canterbury.ac.nz',
      description: 'Two-day challenge for UC and Lincoln University students focused on climate resilience and food systems. $3,000+ in cash and in-kind prizes. Teams of up to 5. Organisers form teams for individual applicants.',
      location: 'Christchurch, New Zealand',
      locationType: 'onsite',
      city: 'Christchurch',
      country: 'New Zealand',
      tags: ['competition', 'entrepreneurship', 'sustainability', 'climate', 'food-systems'],
      skills: ['entrepreneurship', 'innovation', 'sustainability', 'teamwork'],
      industries: ['Sustainability', 'Agriculture', 'Innovation'],
      category: 'Competitions',
      url: 'https://www.canterbury.ac.nz/about-uc/our-structure/faculties/business-faculty/centre-for-entrepreneurship/disrupt-challenge-series/breaking-ground-disrupt-challenge-2026',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: '$3,000+ in prizes' },
      benefits: ['Cash prizes', 'Mentorship', 'Team-building'],
    },
    {
      id: 'comp_uoa_energy_case',
      type: 'competition',
      source: 'curated',
      sourceId: 'uoa_energy_2026',
      title: 'Energy Centre Case Competition',
      organization: 'University of Auckland Case Club',
      organizationUrl: 'https://uoacaseclub.co.nz',
      description: 'Think of innovative ways to transform New Zealand\'s energy sector. Open to all students at any stage of their undergraduate degree. Learn about sustainable energy while developing analytical and presentation skills.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['case-competition', 'energy', 'sustainability', 'innovation'],
      skills: ['business-analysis', 'sustainability', 'presentation', 'research'],
      industries: ['Energy', 'Sustainability'],
      category: 'Competitions',
      url: 'https://uoacaseclub.co.nz/competitions-2026',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 7 * day).toISOString(),
      deadline: new Date(now + 40 * day).toISOString(),
      dates: { deadline: new Date(now + 40 * day).toISOString() },
    },
    {
      id: 'comp_uoa_kearney_case',
      type: 'competition',
      source: 'curated',
      sourceId: 'uoa_kearney_2026',
      title: 'Kearney Case Competition',
      organization: 'University of Auckland Case Club',
      organizationUrl: 'https://uoacaseclub.co.nz',
      description: 'No technical or financial knowledge needed — bring common sense, creativity, and basic commercial know-how. Solve real business challenges and present your strategy to Kearney consultants.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['case-competition', 'consulting', 'strategy', 'kearney', 'business'],
      skills: ['creative-thinking', 'strategy', 'presentation', 'teamwork'],
      industries: ['Consulting', 'Management'],
      category: 'Competitions',
      url: 'https://uoacaseclub.co.nz/competitions-2026',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 2 * day).toISOString(),
      deadline: new Date(now + 50 * day).toISOString(),
      dates: { deadline: new Date(now + 50 * day).toISOString() },
    },
    {
      id: 'comp_uoa_juncture_impact',
      type: 'competition',
      source: 'curated',
      sourceId: 'uoa_juncture_2026',
      title: 'Juncture Impact Investing Case Competition',
      organization: 'University of Auckland Case Club',
      organizationUrl: 'https://uoacaseclub.co.nz',
      description: 'Harness business as a force for social good. Tackle a case on impact investing — explore how capitalism can evolve to enhance wellbeing of people and the planet. Open to all degrees and experience levels.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['case-competition', 'impact-investing', 'social-good', 'sustainability', 'finance'],
      skills: ['impact-investing', 'business-analysis', 'presentation', 'social-impact'],
      industries: ['Finance', 'Social Enterprise'],
      category: 'Competitions',
      url: 'https://uoacaseclub.co.nz/competitions-2026',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 8 * day).toISOString(),
      deadline: new Date(now + 60 * day).toISOString(),
      dates: { deadline: new Date(now + 60 * day).toISOString() },
    },
    {
      id: 'comp_mlh_global',
      type: 'competition',
      source: 'curated',
      sourceId: 'mlh_global_2026',
      title: 'MLH Global Hack Week',
      organization: 'Major League Hacking',
      organizationUrl: 'https://mlh.io',
      description: 'Week-long global hackathon. Build projects, learn new technologies, attend workshops, and compete for prizes. Open to students worldwide, fully remote. All skill levels welcome.',
      location: 'Online',
      locationType: 'remote',
      isRemote: true,
      country: 'International',
      tags: ['hackathon', 'competition', 'programming', 'global', 'remote'],
      skills: ['programming', 'teamwork', 'innovation', 'rapid-prototyping'],
      industries: ['Technology', 'Software'],
      category: 'Competitions',
      url: 'https://mlh.io/seasons/2026/events',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      startDate: new Date(now + 25 * day).toISOString(),
      endDate: new Date(now + 32 * day).toISOString(),
      dates: { startDate: new Date(now + 25 * day).toISOString(), endDate: new Date(now + 32 * day).toISOString() },
      benefits: ['Prizes', 'Workshops', 'Global community', 'Portfolio projects'],
    },
    {
      id: 'comp_uoa_legaltech_hackathon',
      type: 'competition',
      source: 'curated',
      sourceId: 'uoa_legaltech_2026',
      title: 'UoA Legal Tech Hackathon',
      organization: 'University of Auckland Faculty of Law',
      organizationUrl: 'https://www.auckland.ac.nz/hackathon',
      description: 'Combine law and technology to build prototypes that improve access to justice, streamline legal processes, or tackle regulatory challenges. Interdisciplinary teams of law, engineering, and business students work 48 hours with mentors from top NZ law firms.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['hackathon', 'legal-tech', 'law', 'technology', 'innovation'],
      categoryTags: ['hackathon', 'legal-tech'],
      skills: ['programming', 'legal-research', 'design-thinking', 'teamwork', 'rapid-prototyping'],
      industries: ['Legal', 'Technology'],
      category: 'Competitions',
      url: 'https://www.auckland.ac.nz/hackathon',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      deadline: new Date(now + 45 * day).toISOString(),
      startDate: new Date(now + 55 * day).toISOString(),
      endDate: new Date(now + 57 * day).toISOString(),
      dates: {
        deadline: new Date(now + 45 * day).toISOString(),
        startDate: new Date(now + 55 * day).toISOString(),
        endDate: new Date(now + 57 * day).toISOString(),
      },
      benefits: ['Prizes', 'Law firm mentorship', 'Interdisciplinary experience'],
    },
    {
      id: 'comp_nsscc',
      type: 'competition',
      source: 'curated',
      sourceId: 'nsscc_2026',
      title: 'National Secondary Schools Case Competition (NSSCC)',
      organization: 'University of Auckland Case Club',
      organizationUrl: 'https://uoacaseclub.co.nz/nsscc',
      description: 'NZ\'s premier case competition for Year 11-13 secondary school students. Teams analyse a real business scenario and pitch recommendations to industry judges. Semi-finals held online via Zoom; national finals held in-person at the University of Auckland.',
      location: 'Auckland / Online, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['case-competition', 'secondary-school', 'business', 'strategy', 'presentation'],
      categoryTags: ['case-competition', 'secondary-school'],
      skills: ['business-analysis', 'presentation', 'critical-thinking', 'teamwork'],
      industries: ['Business', 'Education'],
      category: 'Competitions',
      url: 'https://uoacaseclub.co.nz/nsscc',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      deadline: new Date(now + 38 * day).toISOString(),
      dates: { deadline: new Date(now + 38 * day).toISOString() },
      benefits: ['National recognition', 'UoA campus experience', 'Industry judge feedback'],
    },
    {
      id: 'comp_nz_physics_maths',
      type: 'competition',
      source: 'curated',
      sourceId: 'nz_physics_maths_2026',
      title: 'NZ Physics and Mathematics Competition',
      organization: 'University of Auckland Physics Department',
      organizationUrl: 'https://www.auckland.ac.nz',
      description: 'Annual STEM competition organised by the UoA Physics Department for NZ secondary and tertiary students. Challenges span theoretical physics, applied mathematics, and problem-solving under timed conditions. Top performers are recognised at a national awards ceremony.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['competition', 'physics', 'mathematics', 'stem', 'academic'],
      categoryTags: ['stem', 'academic'],
      skills: ['physics', 'mathematics', 'problem-solving', 'analytical-thinking'],
      industries: ['Science', 'Education'],
      category: 'Competitions',
      url: 'https://www.auckland.ac.nz',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 10 * day).toISOString(),
      deadline: new Date(now + 70 * day).toISOString(),
      dates: { deadline: new Date(now + 70 * day).toISOString() },
      benefits: ['Awards ceremony', 'Academic recognition', 'STEM networking'],
    },
    {
      id: 'comp_enactus_nz',
      type: 'competition',
      source: 'curated',
      sourceId: 'enactus_nz_2026',
      title: 'Enactus NZ National Competition',
      organization: 'Enactus New Zealand',
      organizationUrl: 'https://enactus.org/country/new-zealand/',
      description: 'University teams present community impact projects they have developed throughout the year. Judged by business leaders on measurable social, economic, and environmental outcomes. Winning team represents NZ at the Enactus World Cup.',
      location: 'New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['competition', 'social-enterprise', 'entrepreneurship', 'community-impact', 'sustainability'],
      categoryTags: ['social-enterprise', 'entrepreneurship'],
      skills: ['social-entrepreneurship', 'project-management', 'presentation', 'leadership', 'teamwork'],
      industries: ['Social Enterprise', 'Non-Profit'],
      category: 'Competitions',
      url: 'https://enactus.org/country/new-zealand/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 12 * day).toISOString(),
      deadline: new Date(now + 80 * day).toISOString(),
      startDate: new Date(now + 90 * day).toISOString(),
      endDate: new Date(now + 91 * day).toISOString(),
      dates: {
        deadline: new Date(now + 80 * day).toISOString(),
        startDate: new Date(now + 90 * day).toISOString(),
        endDate: new Date(now + 91 * day).toISOString(),
      },
      benefits: ['World Cup qualification', 'Business leader judges', 'Community impact'],
    },
    {
      id: 'comp_microsoft_imagine_cup',
      type: 'competition',
      source: 'curated',
      sourceId: 'imagine_cup_2026',
      title: 'Microsoft Imagine Cup 2026',
      organization: 'Microsoft',
      organizationUrl: 'https://imaginecup.microsoft.com/',
      description: 'Global student technology competition. Build an innovative solution using Microsoft Azure, AI, or other Microsoft technologies to address real-world problems. Teams compete through regional rounds for a chance to win USD $100,000 at the World Finals.',
      location: 'Online / Global Finals',
      locationType: 'hybrid',
      isRemote: true,
      country: 'International',
      tags: ['competition', 'technology', 'microsoft', 'azure', 'ai', 'global', 'innovation'],
      categoryTags: ['hackathon', 'technology'],
      skills: ['programming', 'cloud-computing', 'ai', 'product-development', 'teamwork'],
      industries: ['Technology', 'Cloud Computing', 'AI'],
      category: 'Competitions',
      url: 'https://imaginecup.microsoft.com/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 15 * day).toISOString(),
      deadline: new Date(now + 60 * day).toISOString(),
      dates: { deadline: new Date(now + 60 * day).toISOString() },
      compensation: { type: 'paid', currency: 'USD', description: 'Up to $100,000 grand prize' },
      benefits: ['$100K grand prize', 'Azure credits', 'Microsoft mentorship', 'Global exposure'],
    },
    {
      id: 'comp_google_solution_challenge',
      type: 'competition',
      source: 'curated',
      sourceId: 'gdsc_solution_2026',
      title: 'Google Solution Challenge 2026',
      organization: 'Google Developer Student Clubs',
      organizationUrl: 'https://developers.google.com/community/gdsc-solution-challenge',
      description: 'Build a solution using Google technologies (Firebase, Flutter, Google Cloud, TensorFlow, etc.) that addresses one or more of the United Nations\' 17 Sustainable Development Goals. Open to all university students worldwide through GDSC chapters.',
      location: 'Online',
      locationType: 'remote',
      isRemote: true,
      country: 'International',
      tags: ['competition', 'google', 'sdg', 'technology', 'social-impact', 'global'],
      categoryTags: ['hackathon', 'social-impact'],
      skills: ['programming', 'google-cloud', 'mobile-development', 'product-design', 'teamwork'],
      industries: ['Technology', 'Social Impact'],
      category: 'Competitions',
      url: 'https://developers.google.com/community/gdsc-solution-challenge',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 9 * day).toISOString(),
      deadline: new Date(now + 55 * day).toISOString(),
      dates: { deadline: new Date(now + 55 * day).toISOString() },
      benefits: ['Google swag', 'Mentorship from Googlers', 'Global recognition', 'Cloud credits'],
    },
    {
      id: 'comp_aws_build_on',
      type: 'competition',
      source: 'curated',
      sourceId: 'aws_build_on_2026',
      title: 'AWS Build On Challenge',
      organization: 'Amazon Web Services',
      organizationUrl: 'https://aws.amazon.com/education/awseducate/',
      description: 'Cloud computing challenge for students. Design and deploy a scalable application on AWS using services like Lambda, S3, DynamoDB, and SageMaker. Demonstrate cloud architecture best practices and innovation. Winners receive AWS credits and career opportunities.',
      location: 'Online',
      locationType: 'remote',
      isRemote: true,
      country: 'International',
      tags: ['competition', 'aws', 'cloud-computing', 'technology', 'global'],
      categoryTags: ['hackathon', 'cloud'],
      skills: ['cloud-computing', 'aws', 'programming', 'architecture', 'devops'],
      industries: ['Technology', 'Cloud Computing'],
      category: 'Competitions',
      url: 'https://aws.amazon.com/education/awseducate/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 7 * day).toISOString(),
      deadline: new Date(now + 65 * day).toISOString(),
      dates: { deadline: new Date(now + 65 * day).toISOString() },
      benefits: ['AWS credits', 'Career opportunities', 'Cloud certification discounts'],
    },
    {
      id: 'comp_youthhack_nz',
      type: 'competition',
      source: 'curated',
      sourceId: 'youthhack_nz_2026',
      title: 'YouthHack NZ',
      organization: 'YouthHack NZ',
      organizationUrl: 'https://youthhack.nz/',
      description: 'Student-run hackathon series across New Zealand bringing together young developers, designers, and entrepreneurs. Build working prototypes in 24-48 hours, receive mentorship from NZ tech industry professionals, and compete for prizes.',
      location: 'Multiple cities, New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['hackathon', 'youth', 'technology', 'innovation', 'nz'],
      categoryTags: ['hackathon', 'youth'],
      skills: ['programming', 'design', 'entrepreneurship', 'teamwork', 'rapid-prototyping'],
      industries: ['Technology', 'Startups'],
      category: 'Competitions',
      url: 'https://youthhack.nz/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 5 * day).toISOString(),
      startDate: new Date(now + 40 * day).toISOString(),
      endDate: new Date(now + 42 * day).toISOString(),
      dates: {
        startDate: new Date(now + 40 * day).toISOString(),
        endDate: new Date(now + 42 * day).toISOString(),
      },
      benefits: ['Prizes', 'Industry mentorship', 'Portfolio projects', 'NZ tech community access'],
    },
    {
      id: 'comp_nzsscc',
      type: 'competition',
      source: 'curated',
      sourceId: 'nzsscc_2026',
      title: 'NZ Secondary Schools Case Competition (NZSSCC)',
      organization: 'NZSSCC',
      organizationUrl: 'http://www.nzsscc.org/',
      description: 'National case competition open to secondary school students across New Zealand. Teams analyse a business scenario and present strategic recommendations to a panel of judges. Develops critical thinking, communication, and commercial awareness.',
      location: 'New Zealand',
      locationType: 'hybrid',
      country: 'New Zealand',
      tags: ['case-competition', 'secondary-school', 'business', 'national', 'strategy'],
      categoryTags: ['case-competition', 'secondary-school'],
      skills: ['business-analysis', 'critical-thinking', 'presentation', 'teamwork'],
      industries: ['Business', 'Education'],
      category: 'Competitions',
      url: 'http://www.nzsscc.org/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 11 * day).toISOString(),
      deadline: new Date(now + 48 * day).toISOString(),
      dates: { deadline: new Date(now + 48 * day).toISOString() },
      benefits: ['National recognition', 'Judge feedback', 'Business skills development'],
    },
    {
      id: 'comp_chiasma_bio_innovation',
      type: 'competition',
      source: 'curated',
      sourceId: 'chiasma_bio_2026',
      title: 'Chiasma Bio Innovation Challenge',
      organization: 'Chiasma NZ',
      organizationUrl: 'https://chiasma.org.nz/',
      description: 'Biotech innovation competition challenging NZ students to develop creative solutions to pressing biological and health-science problems. Teams pitch to industry leaders from NZ\'s biotech sector. Great entry point into the life-sciences innovation ecosystem.',
      location: 'New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['competition', 'biotech', 'innovation', 'health', 'life-sciences'],
      categoryTags: ['biotech', 'innovation'],
      skills: ['scientific-research', 'innovation', 'presentation', 'teamwork', 'biotech'],
      industries: ['Biotechnology', 'Health', 'Life Sciences'],
      category: 'Competitions',
      url: 'https://chiasma.org.nz/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 8 * day).toISOString(),
      deadline: new Date(now + 52 * day).toISOString(),
      dates: { deadline: new Date(now + 52 * day).toISOString() },
      benefits: ['Biotech industry exposure', 'Mentorship', 'Innovation network'],
    },
    {
      id: 'comp_nz_young_enterprise',
      type: 'competition',
      source: 'curated',
      sourceId: 'yes_2026',
      title: 'NZ Young Enterprise Scheme (YES)',
      organization: 'Young Enterprise Trust',
      organizationUrl: 'https://www.youngenterprise.org.nz/',
      description: 'Year-long business programme and competition for NZ secondary school students. Teams create a real company, develop a product or service, manage finances, and compete at regional and national finals. Develops entrepreneurial mindset and real-world business skills.',
      location: 'Nationwide, New Zealand',
      locationType: 'hybrid',
      country: 'New Zealand',
      tags: ['competition', 'entrepreneurship', 'business', 'secondary-school', 'year-long'],
      categoryTags: ['entrepreneurship', 'secondary-school'],
      skills: ['entrepreneurship', 'business-management', 'marketing', 'financial-literacy', 'teamwork'],
      industries: ['Business', 'Entrepreneurship', 'Education'],
      category: 'Competitions',
      url: 'https://www.youngenterprise.org.nz/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 14 * day).toISOString(),
      startDate: new Date(now + 20 * day).toISOString(),
      endDate: new Date(now + 200 * day).toISOString(),
      dates: {
        startDate: new Date(now + 20 * day).toISOString(),
        endDate: new Date(now + 200 * day).toISOString(),
      },
      benefits: ['Real business experience', 'National finals', 'Scholarships', 'Industry mentors'],
    },
    {
      id: 'comp_robogals_stem',
      type: 'competition',
      source: 'curated',
      sourceId: 'robogals_akl_2026',
      title: 'Robogals STEM Challenge',
      organization: 'Robogals Auckland (University of Auckland Chapter)',
      organizationUrl: 'https://linktr.ee/robogalsakl',
      description: 'Engineering outreach and STEM challenge organised by the UoA Robogals chapter. Focused on promoting diversity in engineering and technology through hands-on robotics and coding challenges. Open to students of all skill levels.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['competition', 'stem', 'robotics', 'engineering', 'diversity', 'outreach'],
      categoryTags: ['stem', 'robotics'],
      skills: ['robotics', 'programming', 'engineering', 'teamwork', 'mentoring'],
      industries: ['Engineering', 'Technology', 'Education'],
      category: 'Competitions',
      url: 'https://linktr.ee/robogalsakl',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      deadline: new Date(now + 35 * day).toISOString(),
      dates: { deadline: new Date(now + 35 * day).toISOString() },
      benefits: ['STEM outreach experience', 'Robotics skills', 'Community impact'],
    },
    {
      id: 'comp_devs_hackathon_nz',
      type: 'competition',
      source: 'curated',
      sourceId: 'devs_hackathon_2026',
      title: 'DEVS Hackathon NZ',
      organization: 'DEVS NZ',
      organizationUrl: 'https://devs.org.nz/',
      description: 'Community-driven hackathon run by the NZ developer community. Build innovative software solutions over a weekend, with tracks spanning web development, mobile apps, data science, and open source. Industry sponsors provide prizes and mentorship.',
      location: 'New Zealand',
      locationType: 'hybrid',
      country: 'New Zealand',
      tags: ['hackathon', 'developer', 'community', 'open-source', 'nz'],
      categoryTags: ['hackathon', 'developer'],
      skills: ['programming', 'web-development', 'mobile-development', 'teamwork', 'open-source'],
      industries: ['Technology', 'Software Development'],
      category: 'Competitions',
      url: 'https://devs.org.nz/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      startDate: new Date(now + 50 * day).toISOString(),
      endDate: new Date(now + 52 * day).toISOString(),
      dates: {
        startDate: new Date(now + 50 * day).toISOString(),
        endDate: new Date(now + 52 * day).toISOString(),
      },
      benefits: ['Prizes', 'NZ dev community networking', 'Sponsor mentorship', 'Portfolio projects'],
    },
    {
      id: 'comp_jane_street_etc',
      type: 'competition',
      source: 'curated',
      sourceId: 'jane_street_etc_2026',
      title: 'Jane Street Electronic Trading Competition',
      organization: 'Jane Street',
      organizationUrl: 'https://www.janestreet.com/join-jane-street/programs-and-events/',
      description: 'Fast-paced quantitative trading simulation where teams compete to build the most profitable trading strategies. Develop algorithms for market-making, arbitrage, and risk management on a simulated exchange. Ideal for students interested in quantitative finance, maths, and computer science.',
      location: 'Online / Various locations',
      locationType: 'hybrid',
      isRemote: true,
      country: 'International',
      tags: ['competition', 'quantitative-finance', 'trading', 'algorithms', 'mathematics'],
      categoryTags: ['finance', 'quantitative'],
      skills: ['quantitative-analysis', 'algorithms', 'programming', 'risk-management', 'mathematics'],
      industries: ['Finance', 'Quantitative Trading', 'Technology'],
      category: 'Competitions',
      url: 'https://www.janestreet.com/join-jane-street/programs-and-events/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 10 * day).toISOString(),
      deadline: new Date(now + 42 * day).toISOString(),
      dates: { deadline: new Date(now + 42 * day).toISOString() },
      benefits: ['Jane Street career pathway', 'Quant finance experience', 'Prizes', 'Top-tier networking'],
    },
  ];
}

export const competitionsConnector: OpportunityConnector = {
  name: 'competitions',
  supportedTypes: ['competition'],
  async fetch(config): Promise<ConnectorResult> {
    const errors: string[] = [];
    let opportunities: Opportunity[] = [];

    try {
      const live = await fetchDevpostHackathons();
      opportunities.push(...live);
      console.log(`[CompetitionsConnector] Scraped ${live.length} from DevPost`);
    } catch (err) {
      errors.push(`DevPost: ${String(err)}`);
    }

    opportunities.push(...getCuratedCompetitions());

    if (config.maxResults) {
      opportunities = opportunities.slice(0, config.maxResults);
    }

    return {
      opportunities,
      source: 'competitions',
      fetchedAt: new Date().toISOString(),
      stats: { fetched: opportunities.length, validated: opportunities.length, errors },
    };
  },
};
