import { Opportunity } from '@/types/opportunities';
import { OpportunityConnector, ConnectorConfig, ConnectorResult } from './types';
import * as cheerio from 'cheerio';

async function fetchEventbriteNZ(): Promise<Opportunity[]> {
  try {
    const res = await fetch(
      'https://www.eventbrite.co.nz/d/new-zealand/student-events/?page=1',
      { headers: { 'User-Agent': 'Gradual-App/2.0', Accept: 'text/html' } }
    );
    if (!res.ok) return [];
    const html = await res.text();
    const $ = cheerio.load(html);
    const events: Opportunity[] = [];

    $('script[type="application/ld+json"]').each((_i, el) => {
      try {
        const data = JSON.parse($(el).text());
        const items = Array.isArray(data) ? data : [data];
        for (const item of items) {
          if (item['@type'] !== 'Event') continue;
          events.push({
            id: `eventbrite_${item.url?.split('-').pop() || Date.now()}`,
            type: 'event',
            source: 'eventbrite',
            sourceId: item.url?.split('-').pop() || '',
            sourceUrl: item.url || '',
            title: item.name || '',
            organization: item.organizer?.name || 'Eventbrite Event',
            description: item.description || item.name || '',
            location: item.location?.name || item.location?.address?.addressLocality || 'New Zealand',
            locationType: item.eventAttendanceMode?.includes('Online') ? 'remote' : 'onsite',
            isRemote: item.eventAttendanceMode?.includes('Online'),
            city: item.location?.address?.addressLocality,
            country: item.location?.address?.addressCountry || 'New Zealand',
            tags: ['event', 'student', 'networking'],
            category: 'Events',
            url: item.url || '#',
            applicationType: 'external',
            status: 'active',
            createdAt: new Date().toISOString(),
            startDate: item.startDate,
            endDate: item.endDate,
            dates: { startDate: item.startDate, endDate: item.endDate },
          });
        }
      } catch { /* skip malformed JSON-LD */ }
    });
    return events;
  } catch (err) {
    console.error('[EventsConnector] Eventbrite fetch failed:', err);
    return [];
  }
}

function getCuratedEvents(): Opportunity[] {
  const now = Date.now();
  const day = 24 * 60 * 60 * 1000;
  return [
    {
      id: 'event_uoa_recruitment_ready',
      type: 'event',
      source: 'curated',
      sourceId: 'uoa_grr_2026',
      title: 'Get Recruitment Ready 2026 - UoA Bootcamp',
      organization: 'University of Auckland Career Development',
      organizationUrl: 'https://www.auckland.ac.nz/en/students/student-support/academic-support/career-development-and-employability-services.html',
      description: 'Half-day bootcamp for penultimate and final year students. Employer panels on hiring practices, workplace professionalism, and career development, followed by networking with refreshments. Four weeks of workshops cover job search, applications, interviews, and workplace readiness.',
      location: 'Engineering Building, City Campus, Auckland',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['career', 'recruitment', 'workshops', 'networking', 'employment'],
      skills: ['interview-skills', 'resume-writing', 'networking', 'professionalism'],
      industries: ['All Industries'],
      category: 'Career Development',
      url: 'https://www.auckland.ac.nz/en/students/student-support/academic-support/career-development-and-employability-services/cdes-events1/get-recruitment-ready.html',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 5 * day).toISOString(),
      startDate: new Date(now + 14 * day).toISOString(),
      dates: { startDate: new Date(now + 14 * day).toISOString() },
      benefits: ['Employer panels', 'Free workshops', 'Networking', 'Career coaching'],
    },
    {
      id: 'event_healthex_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'healthex_2026',
      title: 'HealtheX 2026 - Student Research Conference',
      organization: 'University of Auckland Faculty of Medical and Health Sciences',
      organizationUrl: 'https://healthex.auckland.ac.nz/',
      description: 'Student research conference at UoA Grafton Campus. Present your research, network with peers and academics, receive feedback from experts. Abstract submissions open June 1. Open to all health sciences students.',
      location: 'Grafton Campus, Auckland',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['research', 'conference', 'health-sciences', 'academic', 'presentation'],
      skills: ['research', 'presentation', 'academic-writing'],
      industries: ['Health Sciences', 'Research'],
      category: 'Academic',
      url: 'https://healthex.auckland.ac.nz/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 8 * day).toISOString(),
      startDate: new Date(now + 90 * day).toISOString(),
      dates: { startDate: new Date(now + 90 * day).toISOString() },
    },
    {
      id: 'event_wilnz_conference',
      type: 'event',
      source: 'curated',
      sourceId: 'wilnz_2026',
      title: 'WILNZ Annual Conference 2026 - Work-Integrated Learning',
      organization: 'Work-Integrated Learning New Zealand',
      organizationUrl: 'https://wilnz.nz/conference/',
      description: 'Annual conference at AUT on work-integrated learning, featuring presentations, poster sessions, workshops, and networking. Explore how work placements, internships, and applied projects prepare students for careers.',
      location: 'Auckland University of Technology',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['conference', 'work-integrated-learning', 'internships', 'career', 'education'],
      skills: ['professional-development', 'networking'],
      industries: ['Education', 'All Industries'],
      category: 'Career Development',
      url: 'https://wilnz.nz/conference/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 10 * day).toISOString(),
      startDate: new Date(now + 20 * day).toISOString(),
      dates: { startDate: new Date(now + 20 * day).toISOString() },
    },
    {
      id: 'event_freskival_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'freskival_2026',
      title: 'Freskival - Aotearoa\'s Climate Connection Weekend',
      organization: 'Climate Training Co.',
      description: 'Nationwide climate education workshops in Auckland, Wellington, and other centres. Climate Fresk workshops open to ages 14+. Learn about climate science, connect with the sustainability community, and explore climate solutions.',
      location: 'Multiple cities, New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['climate', 'sustainability', 'workshop', 'education', 'environment'],
      skills: ['sustainability', 'climate-science', 'community-engagement'],
      industries: ['Environment', 'Sustainability'],
      category: 'Environment',
      url: 'https://auckland.scoop.co.nz/2026/04/climate-training-co-announces-freskival-aotearoas-big-weekend-of-climate-connection/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 2 * day).toISOString(),
      startDate: new Date(now + 13 * day).toISOString(),
      endDate: new Date(now + 15 * day).toISOString(),
      dates: { startDate: new Date(now + 13 * day).toISOString(), endDate: new Date(now + 15 * day).toISOString() },
    },
    {
      id: 'event_techweek_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'techweek_2026',
      title: 'Techweek NZ 2026',
      organization: 'NZTech',
      organizationUrl: 'https://techweek.co.nz',
      description: 'New Zealand\'s annual technology festival. Innovation showcases, workshops, meetups, hackathons, and networking events across the country. Free and ticketed events for students and professionals alike.',
      location: 'Multiple cities, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['technology', 'innovation', 'networking', 'workshops', 'startups'],
      skills: ['networking', 'technology', 'innovation'],
      industries: ['Technology', 'Startups'],
      category: 'Technology',
      url: 'https://techweek.co.nz',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      startDate: new Date(now + 35 * day).toISOString(),
      endDate: new Date(now + 42 * day).toISOString(),
      dates: { startDate: new Date(now + 35 * day).toISOString(), endDate: new Date(now + 42 * day).toISOString() },
    },
    {
      id: 'event_startup_weekend_wlg',
      type: 'event',
      source: 'curated',
      sourceId: 'startup_wknd_wlg',
      title: 'Startup Weekend Wellington 2026',
      organization: 'Techstars Startup Weekend',
      organizationUrl: 'https://startupweekend.org',
      description: '54-hour event where participants pitch ideas, form teams, and build real startups from scratch. Mentored by experienced NZ founders and investors. Open to students of all backgrounds.',
      location: 'Wellington, New Zealand',
      locationType: 'onsite',
      city: 'Wellington',
      country: 'New Zealand',
      tags: ['startup', 'entrepreneurship', 'pitching', 'innovation', 'teamwork'],
      skills: ['entrepreneurship', 'pitching', 'teamwork', 'rapid-prototyping'],
      category: 'Entrepreneurship',
      url: 'https://startupweekend.org',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 9 * day).toISOString(),
      startDate: new Date(now + 55 * day).toISOString(),
      endDate: new Date(now + 57 * day).toISOString(),
      dates: { startDate: new Date(now + 55 * day).toISOString(), endDate: new Date(now + 57 * day).toISOString() },
    },
    {
      id: 'event_uoa_eng_tech_expo_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'uoa_eng_tech_expo_2026',
      title: 'UoA Engineering and Technology Expo 2026',
      organization: 'University of Auckland Career Development & Employability Services',
      organizationUrl: 'https://www.auckland.ac.nz/en/students/student-support/academic-support/career-development-and-employability-services.html',
      description: 'Two-day expo featuring 40+ organisations including Atlassian, Jane Street, Fisher & Paykel Healthcare, and Contact Energy. Meet recruiters, learn about grad programmes and internships in engineering and technology. Free for all UoA students.',
      location: 'Engineering Atrium, City Campus, Auckland',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['career-expo', 'engineering', 'technology', 'networking', 'recruitment'],
      skills: ['networking', 'interview-skills', 'engineering'],
      industries: ['Engineering', 'Technology', 'Energy', 'Healthcare Technology'],
      category: 'Career Development',
      url: 'https://www.auckland.ac.nz/en/students/student-support/academic-support/career-development-and-employability-services/cdes-events1/stem-expo.html',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      startDate: new Date(now + 17 * day).toISOString(),
      endDate: new Date(now + 18 * day).toISOString(),
      dates: { startDate: new Date(now + 17 * day).toISOString(), endDate: new Date(now + 18 * day).toISOString() },
      benefits: ['Meet 40+ employers', 'Free entry for UoA students', 'Internship & grad opportunities'],
    },
    {
      id: 'event_aut_ict_eng_expo_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'aut_ict_eng_expo_2026',
      title: 'AUT ICT & Engineering Career Expo 2026',
      organization: 'Auckland University of Technology Employability & Careers',
      organizationUrl: 'https://www.aut.ac.nz/student-life/career-support',
      description: 'Connect with leading ICT and engineering employers at AUT\'s dedicated career expo. Meet recruiters, explore graduate roles and internships, and get career advice. Free, but registration required via Humanitix.',
      location: 'Sir Paul Reeves Building Room 201, AUT City Campus, Auckland',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['career-expo', 'ict', 'engineering', 'recruitment', 'aut'],
      skills: ['networking', 'software-engineering', 'communication'],
      industries: ['ICT', 'Engineering', 'Technology'],
      category: 'Career Development',
      url: 'https://events.humanitix.com/2026-aut-ict-and-engineering-career-expo-registration',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 12 * day).toISOString(),
      startDate: new Date(now - 12 * day).toISOString(),
      dates: { startDate: new Date(now - 12 * day).toISOString() },
      benefits: ['Free entry', 'Direct employer access', 'Registration via Humanitix'],
    },
    {
      id: 'event_uoa_biz_law_expo_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'uoa_biz_law_expo_2026',
      title: 'UoA Business and Law Expo 2026',
      organization: 'University of Auckland Career Development & Employability Services',
      organizationUrl: 'https://www.auckland.ac.nz/en/students/student-support/academic-support/career-development-and-employability-services.html',
      description: 'Annual expo connecting business and law students with top employers. Network with firms in finance, consulting, law, accounting, and more. Learn about grad programmes, summer clerkships, and internships.',
      location: 'University of Auckland, City Campus',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['career-expo', 'business', 'law', 'finance', 'recruitment'],
      skills: ['networking', 'commercial-awareness', 'communication'],
      industries: ['Finance', 'Consulting', 'Law', 'Accounting'],
      category: 'Career Development',
      url: 'https://www.auckland.ac.nz/en/students/student-support/academic-support/career-development-and-employability-services/for-employers/career-expos.html',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 25 * day).toISOString(),
      startDate: new Date(now - 23 * day).toISOString(),
      dates: { startDate: new Date(now - 23 * day).toISOString() },
    },
    {
      id: 'event_uoa_intern_grad_expo_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'uoa_intern_grad_expo_2026',
      title: 'UoA Internship and Graduate Career Expo 2026',
      organization: 'University of Auckland Career Development & Employability Services',
      organizationUrl: 'https://www.auckland.ac.nz/en/students/student-support/academic-support/career-development-and-employability-services.html',
      description: 'The largest UoA career expo of the year for students seeking internships and graduate roles across all industries. Employers from tech, engineering, government, FMCG, consulting, and more.',
      location: 'University of Auckland, City Campus',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['career-expo', 'internship', 'graduate', 'recruitment', 'all-industries'],
      skills: ['networking', 'interview-skills', 'resume-writing'],
      industries: ['All Industries'],
      category: 'Career Development',
      url: 'https://www.auckland.ac.nz/en/students/student-support/academic-support/career-development-and-employability-services/for-employers/career-expos.html',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      startDate: new Date(now + 116 * day).toISOString(),
      dates: { startDate: new Date(now + 116 * day).toISOString() },
      benefits: ['Open to all faculties', 'Internship & grad roles', 'Free for UoA students'],
    },
    {
      id: 'event_uoa_health_wellness_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'uoa_health_wellness_2026',
      title: 'UoA Health and Wellness Careers Event 2026',
      organization: 'University of Auckland Career Development & Employability Services',
      organizationUrl: 'https://www.auckland.ac.nz/en/students/student-support/academic-support/career-development-and-employability-services.html',
      description: 'Dedicated careers event for health and wellness students. Meet employers from DHBs, private health providers, community organisations, and research institutions. Explore career pathways in nursing, pharmacy, public health, and more.',
      location: 'University of Auckland, Grafton Campus',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['career-event', 'health', 'wellness', 'nursing', 'pharmacy'],
      skills: ['networking', 'clinical-skills', 'health-communication'],
      industries: ['Health', 'Wellness', 'Public Health', 'Pharmaceuticals'],
      category: 'Career Development',
      url: 'https://www.auckland.ac.nz/en/students/student-support/academic-support/career-development-and-employability-services/cdes-events1/cdes-health-and-wellness.html',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 7 * day).toISOString(),
      startDate: new Date(now + 172 * day).toISOString(),
      dates: { startDate: new Date(now + 172 * day).toISOString() },
    },
    {
      id: 'event_uoa_summer_work_popup_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'uoa_summer_work_popup_2026',
      title: 'UoA Summer Work Pop-up 2026',
      organization: 'University of Auckland Career Development & Employability Services',
      organizationUrl: 'https://www.auckland.ac.nz/en/students/student-support/academic-support/career-development-and-employability-services.html',
      description: 'Quick-fire event for summer job seekers. Drop in to meet employers hiring for summer roles, casual work, and holiday placements. No appointment needed — just show up and chat with recruiters.',
      location: 'University of Auckland, City Campus',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['summer-work', 'casual', 'recruitment', 'drop-in', 'part-time'],
      skills: ['networking', 'communication'],
      industries: ['All Industries'],
      category: 'Career Development',
      url: 'https://www.auckland.ac.nz/en/students/student-support/academic-support/career-development-and-employability-services/for-employers/career-expos.html',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 1 * day).toISOString(),
      startDate: new Date(now + 186 * day).toISOString(),
      dates: { startDate: new Date(now + 186 * day).toISOString() },
      benefits: ['No registration needed', 'Summer & casual roles', 'Drop-in format'],
    },
    {
      id: 'event_uoa_clubs_expo_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'uoa_clubs_expo_2026',
      title: 'UoA Clubs Expo 2026 (Te Whakaaturanga Karapu)',
      organization: 'University of Auckland Students\' Association (AUSA)',
      organizationUrl: 'https://auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies.html',
      description: 'The biggest student event of the year — 250+ clubs and societies showcase at Semester 1 Clubs Expo. From cultural clubs to tech societies, sports teams to volunteer organisations, find your community at UoA.',
      location: 'University of Auckland, City Campus',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['clubs', 'societies', 'student-life', 'community', 'networking'],
      skills: ['leadership', 'teamwork', 'community-engagement'],
      industries: ['Student Life'],
      category: 'Community',
      url: 'https://auckland.ac.nz/en/on-campus/life-on-campus/clubs-societies/clubs-expo.html',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 15 * day).toISOString(),
      startDate: new Date(now + 7 * day).toISOString(),
      endDate: new Date(now + 9 * day).toISOString(),
      dates: { startDate: new Date(now + 7 * day).toISOString(), endDate: new Date(now + 9 * day).toISOString() },
      benefits: ['250+ clubs', 'Free to attend', 'Sign up on the spot'],
    },
    {
      id: 'event_aiesec_nz_conference_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'aiesec_nz_conf_2026',
      title: 'AIESEC NZ National Conference 2026',
      organization: 'AIESEC New Zealand',
      organizationUrl: 'https://aiesec.org.nz/',
      description: 'Student leadership conference bringing together young leaders from across New Zealand. Workshops on leadership development, social impact, and international exchange opportunities. Connect with a global network of 100,000+ students.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['leadership', 'conference', 'international', 'exchange', 'social-impact'],
      skills: ['leadership', 'cross-cultural-communication', 'project-management'],
      industries: ['Non-Profit', 'International Development'],
      category: 'Leadership',
      url: 'https://aiesec.org.nz/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      startDate: new Date(now + 45 * day).toISOString(),
      endDate: new Date(now + 47 * day).toISOString(),
      dates: { startDate: new Date(now + 45 * day).toISOString(), endDate: new Date(now + 47 * day).toISOString() },
      benefits: ['Global network access', 'International exchange info', 'Leadership workshops'],
    },
    {
      id: 'event_auckland_ai_meetup',
      type: 'event',
      source: 'curated',
      sourceId: 'akl_ai_meetup_2026',
      title: 'Auckland AI Meetup',
      organization: 'Auckland AI Meetup Group',
      organizationUrl: 'https://www.meetup.com/auckland-ai-meetup/',
      description: 'Regular community meetups covering AI and machine learning topics. Talks from industry practitioners and researchers, demos of cutting-edge projects, and networking with Auckland\'s AI community. Open to students at all levels.',
      location: 'Various venues, Auckland',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['ai', 'machine-learning', 'meetup', 'networking', 'technology'],
      skills: ['machine-learning', 'data-science', 'python', 'networking'],
      industries: ['Technology', 'AI/ML', 'Research'],
      category: 'Technology',
      url: 'https://www.meetup.com/auckland-ai-meetup/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 2 * day).toISOString(),
      startDate: new Date(now + 10 * day).toISOString(),
      dates: { startDate: new Date(now + 10 * day).toISOString() },
      benefits: ['Free to attend', 'Industry talks', 'Student-friendly'],
    },
    {
      id: 'event_nz_se_conference_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'nz_se_conf_2026',
      title: 'NZ Software Engineering Conference 2026',
      organization: 'Software Engineering Society of New Zealand',
      organizationUrl: 'https://sesociety.nz/',
      description: 'Annual conference for software engineering practitioners in New Zealand. Technical talks, panel discussions, and workshops on modern software development practices, architecture, and tooling. Student tickets available at reduced rates.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['software-engineering', 'conference', 'technical', 'development', 'architecture'],
      skills: ['software-engineering', 'system-design', 'agile'],
      industries: ['Technology', 'Software Development'],
      category: 'Technology',
      url: 'https://sesociety.nz/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 11 * day).toISOString(),
      startDate: new Date(now + 70 * day).toISOString(),
      endDate: new Date(now + 71 * day).toISOString(),
      dates: { startDate: new Date(now + 70 * day).toISOString(), endDate: new Date(now + 71 * day).toISOString() },
      benefits: ['Student discount', 'Technical workshops', 'Industry networking'],
    },
    {
      id: 'event_google_io_extended_akl_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'google_io_ext_akl_2026',
      title: 'Google I/O Extended Auckland 2026',
      organization: 'Google Developer Group on Campus - UoA',
      organizationUrl: 'https://linktr.ee/gdgcuoa',
      description: 'Watch party and hands-on workshops for Google I/O, hosted by GDG on Campus UoA. Experience the latest Google developer announcements, try new APIs, and build projects with fellow students. Pizza and swag provided.',
      location: 'University of Auckland, City Campus',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['google', 'developer', 'workshops', 'watch-party', 'gdg'],
      skills: ['android', 'web-development', 'cloud', 'ai'],
      industries: ['Technology'],
      category: 'Technology',
      url: 'https://linktr.ee/gdgcuoa',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      startDate: new Date(now + 50 * day).toISOString(),
      dates: { startDate: new Date(now + 50 * day).toISOString() },
      benefits: ['Free entry', 'Hands-on workshops', 'Pizza & swag'],
    },
    {
      id: 'event_uoa_scisa_events_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'uoa_scisa_2026',
      title: 'UoA Science Students\' Association Events',
      organization: 'Science Students\' Association (SciSA)',
      organizationUrl: 'https://linktr.ee/SciSA',
      description: 'Science networking events, study sessions, and career panels run by SciSA throughout the year. Connect with fellow science students, hear from industry professionals, and get academic support from senior students.',
      location: 'University of Auckland, City Campus',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['science', 'networking', 'study', 'career-panels', 'student-association'],
      skills: ['networking', 'research', 'science-communication'],
      industries: ['Science', 'Research', 'Technology'],
      category: 'Academic',
      url: 'https://linktr.ee/SciSA',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 1 * day).toISOString(),
      startDate: new Date(now + 5 * day).toISOString(),
      dates: { startDate: new Date(now + 5 * day).toISOString() },
      benefits: ['Free for science students', 'Career panels', 'Study support'],
    },
    {
      id: 'event_nzgdc_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'nzgdc_2026',
      title: 'NZ Game Developers Conference 2026',
      organization: 'New Zealand Game Developers Association',
      organizationUrl: 'https://nzgdc.com/',
      description: 'Aotearoa\'s premier game development conference. Talks from local and international game devs, postmortems, technical deep-dives, and career workshops. Student passes available. Network with studios like Grinding Gear Games, RocketWerkz, and more.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['game-development', 'conference', 'creative', 'programming', 'design'],
      skills: ['game-development', 'programming', 'creative-design', '3d-art'],
      industries: ['Game Development', 'Creative Technology'],
      category: 'Technology',
      url: 'https://nzgdc.com/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 8 * day).toISOString(),
      startDate: new Date(now + 80 * day).toISOString(),
      endDate: new Date(now + 82 * day).toISOString(),
      dates: { startDate: new Date(now + 80 * day).toISOString(), endDate: new Date(now + 82 * day).toISOString() },
      benefits: ['Student passes available', 'Industry networking', 'Career workshops'],
    },
    {
      id: 'event_creative_tech_fest_akl_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'creative_tech_fest_2026',
      title: 'Creative Tech Fest Auckland 2026',
      organization: 'Creative Tech Fest',
      organizationUrl: 'https://creativetechfest.nz/',
      description: 'A festival at the intersection of technology and creative arts. Interactive installations, VR/AR showcases, digital art exhibitions, creative coding workshops, and talks from artists and technologists pushing boundaries.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['creative-tech', 'digital-art', 'vr', 'ar', 'workshops', 'installations'],
      skills: ['creative-coding', 'digital-art', 'vr-ar', 'design'],
      industries: ['Creative Technology', 'Digital Arts', 'Design'],
      category: 'Technology',
      url: 'https://creativetechfest.nz/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 5 * day).toISOString(),
      startDate: new Date(now + 95 * day).toISOString(),
      endDate: new Date(now + 97 * day).toISOString(),
      dates: { startDate: new Date(now + 95 * day).toISOString(), endDate: new Date(now + 97 * day).toISOString() },
      benefits: ['Student discount', 'Hands-on workshops', 'Interactive installations'],
    },
    {
      id: 'event_shesharp_nz_2026',
      type: 'event',
      source: 'curated',
      sourceId: 'shesharp_nz_2026',
      title: 'SheSharp NZ - Women in Tech Events',
      organization: 'SheSharp NZ',
      organizationUrl: 'https://shesharp.co.nz/',
      description: 'Events for women and gender-diverse people in technology. Workshops on coding, career development, and leadership. Networking with women in the NZ tech industry. Mentoring circles and panel discussions with senior tech leaders.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['women-in-tech', 'diversity', 'networking', 'workshops', 'mentoring'],
      skills: ['networking', 'leadership', 'coding', 'career-development'],
      industries: ['Technology'],
      category: 'Community',
      url: 'https://shesharp.co.nz/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      startDate: new Date(now + 21 * day).toISOString(),
      dates: { startDate: new Date(now + 21 * day).toISOString() },
      benefits: ['Free workshops', 'Mentoring circles', 'Supportive community'],
    },
  ];
}

export const eventsConnector: OpportunityConnector = {
  name: 'events',
  supportedTypes: ['event'],
  async fetch(config): Promise<ConnectorResult> {
    const errors: string[] = [];
    let opportunities: Opportunity[] = [];

    try {
      const live = await fetchEventbriteNZ();
      opportunities.push(...live);
      console.log(`[EventsConnector] Scraped ${live.length} from Eventbrite`);
    } catch (err) {
      errors.push(`Eventbrite: ${String(err)}`);
    }

    opportunities.push(...getCuratedEvents());

    if (config.maxResults) {
      opportunities = opportunities.slice(0, config.maxResults);
    }

    return {
      opportunities,
      source: 'events',
      fetchedAt: new Date().toISOString(),
      stats: { fetched: opportunities.length, validated: opportunities.length, errors },
    };
  },
};
