import { Opportunity } from '@/types/opportunities';
import { OpportunityConnector, ConnectorConfig, ConnectorResult } from './types';
import * as cheerio from 'cheerio';

async function fetchGradNZInternships(): Promise<Opportunity[]> {
  try {
    const res = await fetch('https://gradnewzealand.nz/internships', {
      headers: { 'User-Agent': 'Gradual-App/2.0', Accept: 'text/html' },
    });
    if (!res.ok) return [];
    const html = await res.text();
    const $ = cheerio.load(html);
    const internships: Opportunity[] = [];

    $('a[href*="/internship"], a[href*="/graduate-job"]').each((_i, el) => {
      const title = $(el).text().trim();
      const href = $(el).attr('href') || '';
      if (!title || title.length < 10 || title.length > 200) return;
      if (['Browse', 'Search', 'Sign in', 'Register', 'Home'].some(s => title.includes(s))) return;

      const fullUrl = href.startsWith('http') ? href : `https://gradnewzealand.nz${href}`;
      const org = $(el).closest('.listing, .card, article').find('.company, .employer, .org').text().trim() || 'Unknown';

      internships.push({
        id: `gradnz_intern_${title.toLowerCase().replace(/[^a-z0-9]/g, '_').slice(0, 60)}`,
        type: 'internship',
        source: 'gradnewzealand',
        sourceId: href,
        sourceUrl: fullUrl,
        title,
        organization: org,
        description: `${title} — an internship listed on GradNewZealand. Visit the listing for full details on requirements and how to apply.`,
        location: 'New Zealand',
        country: 'New Zealand',
        tags: ['internship', 'graduate', 'new-zealand'],
        category: 'Internships',
        url: fullUrl,
        applicationType: 'external',
        status: 'active',
        createdAt: new Date().toISOString(),
      });
    });
    return internships;
  } catch (err) {
    console.error('[InternshipsConnector] GradNZ scrape failed:', err);
    return [];
  }
}

async function fetchProspleNZInternships(): Promise<Opportunity[]> {
  try {
    const res = await fetch('https://nz.prosple.com/search?opportunity_types=internships', {
      headers: { 'User-Agent': 'Gradual-App/2.0', Accept: 'text/html' },
    });
    if (!res.ok) return [];
    const html = await res.text();
    const $ = cheerio.load(html);
    const internships: Opportunity[] = [];

    $('a[href*="/graduate-employers/"]').each((_i, el) => {
      const title = $(el).text().trim();
      const href = $(el).attr('href') || '';
      if (!title || title.length < 5 || title.length > 200) return;
      if (['Search', 'Filter', 'Login', 'Sign up'].some(s => title.includes(s))) return;

      const fullUrl = href.startsWith('http') ? href : `https://nz.prosple.com${href}`;

      internships.push({
        id: `prosple_intern_${title.toLowerCase().replace(/[^a-z0-9]/g, '_').slice(0, 60)}`,
        type: 'internship',
        source: 'prosple',
        sourceId: href,
        sourceUrl: fullUrl,
        title: `${title} Internship`,
        organization: title,
        description: `Internship opportunity at ${title} listed on Prosple NZ. Check the listing for application details, eligibility, and deadlines.`,
        location: 'New Zealand',
        country: 'New Zealand',
        tags: ['internship', 'graduate', 'new-zealand'],
        category: 'Internships',
        url: fullUrl,
        applicationType: 'external',
        status: 'active',
        createdAt: new Date().toISOString(),
      });
    });
    return internships;
  } catch (err) {
    console.error('[InternshipsConnector] Prosple NZ scrape failed:', err);
    return [];
  }
}

function getCuratedInternships(): Opportunity[] {
  const now = Date.now();
  const day = 24 * 60 * 60 * 1000;
  return [
    {
      id: 'intern_deloitte_nz_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'deloitte_nz_summer_2026',
      title: 'Deloitte NZ Summer Internship 2026/27',
      organization: 'Deloitte New Zealand',
      organizationUrl: 'https://www.deloitte.com/nz',
      description: 'Deloitte\'s flagship summer vacation programme for penultimate-year students. Work across Audit & Assurance, Tax & Legal, Consulting, Technology & Transformation, AI & Data, or Corporate Finance in a collaborative, high-impact environment.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'big-four', 'consulting', 'summer', 'professional-services'],
      skills: ['analytical-thinking', 'teamwork', 'communication', 'problem-solving'],
      industries: ['Professional Services', 'Consulting', 'Accounting'],
      category: 'Internships',
      url: 'https://deloitte.com/nz/en/careers/students/summer-vacation-program-careers.html',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 5 * day).toISOString(),
      dates: { startDate: '2026-11-01', endDate: '2027-02-28' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid summer internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Penultimate year students. Streams: Audit, Tax, Consulting, Tech, AI & Data, Corporate Finance. Offices in Auckland, Wellington, Christchurch.',
      },
      benefits: ['Professional development', 'Mentorship', 'Networking', 'Pathway to graduate role'],
    },
    {
      id: 'intern_pwc_nz_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'pwc_nz_summer_2026',
      title: 'PwC NZ Summer Internship Programme',
      organization: 'PwC New Zealand',
      organizationUrl: 'https://www.pwc.co.nz',
      description: 'PwC\'s summer internship gives penultimate-year students real client experience across Audit & Assurance, Consulting, Tax, and Deals. Build technical skills and professional networks in one of the world\'s largest professional services firms.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'big-four', 'audit', 'consulting', 'tax', 'summer'],
      skills: ['analytical-thinking', 'communication', 'client-management', 'financial-analysis'],
      industries: ['Professional Services', 'Consulting', 'Accounting'],
      category: 'Internships',
      url: 'https://www.pwc.co.nz/careers/studentcareers/summer-internship-programme.html',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      dates: { startDate: '2026-11-01', endDate: '2027-02-28' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid summer internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Penultimate year students. Lines of service: Audit & Assurance, Consulting, Tax, Deals. Auckland and Wellington offices.',
      },
      benefits: ['Client exposure', 'Professional development', 'Mentorship', 'Graduate pathway'],
    },
    {
      id: 'intern_ey_nz_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'ey_nz_intern_2026',
      title: 'EY NZ 2026/27 Internship Programme',
      organization: 'EY New Zealand',
      organizationUrl: 'https://www.ey.com/en_nz',
      description: 'EY\'s internship programme offers hands-on experience across Assurance, Consulting, Strategy & Transactions, and Tax. Develop your career with one of the Big Four while working on real engagements alongside experienced professionals.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'big-four', 'assurance', 'consulting', 'strategy', 'tax'],
      skills: ['analytical-thinking', 'teamwork', 'financial-analysis', 'communication'],
      industries: ['Professional Services', 'Consulting', 'Accounting'],
      category: 'Internships',
      url: 'https://www.ey.com/en_nz/careers/internship-programme-2026',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 7 * day).toISOString(),
      dates: { startDate: '2026-11-01', endDate: '2027-02-28' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid summer internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Multiple service lines across EY NZ offices',
      },
      benefits: ['Real client work', 'Professional development', 'EY Badges', 'Graduate pathway'],
    },
    {
      id: 'intern_kpmg_nz_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'kpmg_nz_intern_2026',
      title: 'KPMG NZ 2026 Internship Programme',
      organization: 'KPMG New Zealand',
      organizationUrl: 'https://www.kpmg.com/nz',
      description: 'KPMG\'s early careers programme places interns in Audit, Tax, Advisory, or Deal Advisory teams. Gain exposure to diverse clients, develop professional skills, and experience the culture of a leading professional services firm.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'big-four', 'audit', 'advisory', 'deal-advisory', 'tax'],
      skills: ['analytical-thinking', 'communication', 'financial-analysis', 'problem-solving'],
      industries: ['Professional Services', 'Consulting', 'Accounting'],
      category: 'Internships',
      url: 'https://www.kpmg.com/nz/en/careers/early-careers.html',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      deadline: '2026-03-27T23:59:59.000Z',
      dates: { deadline: '2026-03-27T23:59:59.000Z' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid summer internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Applications closed 27 Mar 2026. Streams: Audit, Tax, Advisory, Deal Advisory.',
      },
      benefits: ['Client exposure', 'Training programme', 'Mentorship', 'Graduate pathway'],
    },
    {
      id: 'intern_macquarie_auckland_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'macquarie_capital_auckland_2026',
      title: 'Macquarie Capital Summer Intern – Auckland',
      organization: 'Macquarie Group',
      organizationUrl: 'https://www.macquarie.com',
      description: 'A prestigious 10-week summer internship in Macquarie Capital\'s Auckland office covering corporate M&A advisory and equity capital markets. Ideal for students interested in investment banking and financial advisory in the NZ market.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'investment-banking', 'finance', 'capital-markets', 'mergers-acquisitions'],
      skills: ['financial-modelling', 'valuation', 'analytical-thinking', 'excel', 'communication'],
      industries: ['Investment Banking', 'Finance', 'Capital Markets'],
      category: 'Internships',
      url: 'https://recruitment.macquarie.com/en_US/careers/JobDetail/2026-27-Macquarie-Capital-Summer-Internship-Program-Auckland-New-Zealand/20485',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      dates: { startDate: '2026-11-30', endDate: '2027-02-12' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Competitive paid internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Penultimate year students. 30 Nov 2026 – 12 Feb 2027. Corporate M&A and equity capital markets.',
      },
      benefits: ['Investment banking exposure', 'Senior mentorship', 'Networking', 'Graduate pathway'],
    },
    {
      id: 'intern_deloitte_ai_data_auckland_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'deloitte_ai_data_akl_2026',
      title: 'Deloitte AI & Data Intern – Auckland',
      organization: 'Deloitte New Zealand',
      organizationUrl: 'https://www.deloitte.com/nz',
      description: 'Specialist AI and data consulting internship within Deloitte NZ\'s Technology & Transformation practice. Work on real AI/ML and data analytics projects for major NZ organisations alongside leading practitioners.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'artificial-intelligence', 'data', 'consulting', 'machine-learning', 'analytics'],
      skills: ['python', 'data-analysis', 'machine-learning', 'sql', 'communication'],
      industries: ['Technology', 'Consulting', 'AI & Data'],
      category: 'Internships',
      url: 'https://jobs.smartrecruiters.com/DeloitteNZ/6000000000901787-2026-2027-intern-artificial-intelligence-data-auckland',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 2 * day).toISOString(),
      dates: { startDate: '2026-11-01', endDate: '2027-02-28' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid summer internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Students studying computer science, data science, statistics, or related fields',
      },
      benefits: ['AI/ML project experience', 'Technical mentorship', 'Consulting skills', 'Graduate pathway'],
    },
    {
      id: 'intern_eagle_tech_gis_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'eagle_tech_gis_summer_2026',
      title: 'Eagle Technology GIS Summer Intern',
      organization: 'Eagle Technology',
      organizationUrl: 'https://www.eagle.co.nz',
      description: 'A 10-week summer internship working with ArcGIS and spatial technology at New Zealand\'s leading GIS company. Gain hands-on experience in geospatial data, mapping, and location intelligence across real-world projects.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'gis', 'geospatial', 'technology', 'mapping', 'summer'],
      skills: ['gis', 'arcgis', 'spatial-analysis', 'python', 'data-visualisation'],
      industries: ['Technology', 'Geospatial', 'Environmental'],
      category: 'Internships',
      url: 'https://www.eagle.co.nz/summer-interns',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 8 * day).toISOString(),
      dates: { startDate: '2026-11-01', endDate: '2027-02-15' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid 10-week internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: '10 weeks Nov–Feb. Offices in Auckland, Wellington, and Christchurch.',
      },
      benefits: ['ArcGIS training', 'Real project experience', 'Mentorship'],
    },
    {
      id: 'intern_uoa_it_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'uoa_it_internship_2026',
      title: 'University of Auckland IT Internship',
      organization: 'University of Auckland',
      organizationUrl: 'https://www.auckland.ac.nz',
      description: 'A 400-hour paid IT internship within the University of Auckland\'s technology division. Gain experience in software development, platform engineering, and enterprise IT supporting one of NZ\'s largest organisations.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'technology', 'software-development', 'university', 'it'],
      skills: ['software-development', 'platform-engineering', 'agile', 'communication'],
      industries: ['Technology', 'Education', 'IT'],
      category: 'Internships',
      url: 'https://www.careers.auckland.ac.nz/career/it-interns-university-of-auckland-technology-graduate-programme/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 10 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: '400-hour paid internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: '400-hour programme. Software development and platform engineering streams.',
      },
      benefits: ['Enterprise IT experience', 'Mentorship', 'Flexible hours'],
    },
    {
      id: 'intern_fisher_paykel_healthcare_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'fph_summer_2026',
      title: 'Fisher & Paykel Healthcare Summer Intern',
      organization: 'Fisher & Paykel Healthcare',
      organizationUrl: 'https://www.fphcare.com',
      description: 'Summer internship at a global leader in respiratory care and acute care products. Work in engineering, technology, or business functions at their Auckland campus, contributing to medical devices that improve patient outcomes worldwide.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'medical-devices', 'engineering', 'healthcare', 'summer'],
      skills: ['engineering', 'problem-solving', 'teamwork', 'technical-skills'],
      industries: ['Healthcare', 'Medical Devices', 'Engineering'],
      category: 'Internships',
      url: 'https://www.fphcare.com/nz/careers/students-graduates/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 9 * day).toISOString(),
      dates: { startDate: '2026-11-01', endDate: '2027-02-28' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid summer internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Engineering, technology, and business streams. Auckland campus.',
      },
      benefits: ['Medtech experience', 'Global company', 'Purpose-driven work', 'Graduate pathway'],
    },
    {
      id: 'intern_fonterra_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'fonterra_summer_2026',
      title: 'Fonterra Summer Internship',
      organization: 'Fonterra',
      organizationUrl: 'https://www.fonterra.com',
      description: 'Summer internship at the world\'s largest dairy exporter. Gain experience across supply chain, marketing, finance, operations, or science & technology in a global co-operative that processes 30% of the world\'s dairy exports.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'fmcg', 'dairy', 'supply-chain', 'marketing', 'finance', 'summer'],
      skills: ['analytical-thinking', 'project-management', 'communication', 'teamwork'],
      industries: ['FMCG', 'Agriculture', 'Supply Chain', 'Manufacturing'],
      category: 'Internships',
      url: 'https://careers.fonterra.com/en/early-careers',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      dates: { startDate: '2026-11-01', endDate: '2027-02-28' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid summer internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Multiple streams: dairy/supply chain/marketing/finance. Auckland and Hamilton offices.',
      },
      benefits: ['Global FMCG exposure', 'NZ industry leader', 'Mentorship', 'Graduate pathway'],
    },
    {
      id: 'intern_air_nz_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'air_nz_summer_2026',
      title: 'Air New Zealand Summer Intern',
      organization: 'Air New Zealand',
      organizationUrl: 'https://www.airnewzealand.co.nz',
      description: 'Summer internship at New Zealand\'s national carrier. Work in technology, engineering, or commercial teams at Air NZ\'s Auckland campus, contributing to one of the world\'s most awarded airlines.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'aviation', 'technology', 'engineering', 'summer'],
      skills: ['analytical-thinking', 'communication', 'teamwork', 'problem-solving'],
      industries: ['Aviation', 'Technology', 'Transport'],
      category: 'Internships',
      url: 'https://careers.airnewzealand.co.nz/early-careers',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 7 * day).toISOString(),
      dates: { startDate: '2026-11-01', endDate: '2027-02-28' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid summer internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Technology, engineering, and commercial streams. Auckland-based.',
      },
      benefits: ['Iconic NZ brand', 'Travel benefits', 'Mentorship', 'Graduate pathway'],
    },
    {
      id: 'intern_xero_nz_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'xero_intern_2026',
      title: 'Xero Intern Programme',
      organization: 'Xero',
      organizationUrl: 'https://www.xero.com',
      description: 'Internship at Xero, the NZ-founded global cloud accounting platform. Work in software engineering, product management, or design, building features used by millions of small businesses worldwide.',
      location: 'Wellington, New Zealand',
      locationType: 'hybrid',
      city: 'Wellington',
      country: 'New Zealand',
      tags: ['internship', 'software-engineering', 'product', 'design', 'saas', 'cloud'],
      skills: ['software-development', 'product-thinking', 'design', 'agile', 'cloud-computing'],
      industries: ['Technology', 'SaaS', 'Fintech'],
      category: 'Internships',
      url: 'https://www.xero.com/nz/about/careers/interns/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Software engineering, product, and design streams. Wellington and Auckland offices.',
      },
      benefits: ['Global SaaS product', 'Technical mentorship', 'Beautiful offices', 'Graduate pathway'],
    },
    {
      id: 'intern_anz_nz_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'anz_nz_intern_2026',
      title: 'ANZ NZ Graduate & Intern Programme',
      organization: 'ANZ Bank New Zealand',
      organizationUrl: 'https://www.anz.co.nz',
      description: 'Internship at one of NZ\'s largest banks. Gain experience in banking, finance, technology, or risk management, working on real projects that impact millions of customers across New Zealand and the Pacific.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'banking', 'finance', 'technology', 'risk-management'],
      skills: ['financial-analysis', 'data-analysis', 'communication', 'problem-solving'],
      industries: ['Banking', 'Finance', 'Technology'],
      category: 'Internships',
      url: 'https://www.anz.co.nz/about-us/careers/programs/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 5 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Banking, finance, and technology streams',
      },
      benefits: ['Major bank experience', 'Rotation opportunities', 'Mentorship', 'Graduate pathway'],
    },
    {
      id: 'intern_beca_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'beca_summer_2026',
      title: 'Beca Summer Intern',
      organization: 'Beca',
      organizationUrl: 'https://www.beca.com',
      description: 'Summer internship at Beca, Australasia\'s largest employee-owned professional services consultancy. Work on engineering and advisory projects across infrastructure, buildings, water, and environmental sectors in NZ.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'engineering', 'infrastructure', 'advisory', 'environment', 'summer'],
      skills: ['engineering', 'project-management', 'technical-skills', 'teamwork'],
      industries: ['Engineering', 'Infrastructure', 'Advisory'],
      category: 'Internships',
      url: 'https://www.beca.com/careers/graduates-and-interns',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 8 * day).toISOString(),
      dates: { startDate: '2026-11-01', endDate: '2027-02-28' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid summer internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Engineering and advisory streams. Auckland, Wellington, Hamilton, Tauranga, and Christchurch offices.',
      },
      benefits: ['Employee-owned firm', 'Multi-disciplinary projects', 'Mentorship', 'Graduate pathway'],
    },
    {
      id: 'intern_fletcher_building_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'fletcher_building_intern_2026',
      title: 'Fletcher Building Intern Programme',
      organization: 'Fletcher Building',
      organizationUrl: 'https://www.fletcherbuilding.com',
      description: 'Internship at NZ\'s largest building materials and construction company. Gain practical experience across construction, manufacturing, engineering, and corporate functions while contributing to projects shaping New Zealand\'s built environment.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'construction', 'building', 'engineering', 'manufacturing'],
      skills: ['engineering', 'project-management', 'communication', 'problem-solving'],
      industries: ['Construction', 'Building Materials', 'Engineering'],
      category: 'Internships',
      url: 'https://www.fletcherbuilding.com/careers/graduate-programme/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Construction, building, and engineering streams. Auckland-based.',
      },
      benefits: ['NZX-listed company', 'Hands-on projects', 'Mentorship', 'Graduate pathway'],
    },
    {
      id: 'intern_datacom_nz_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'datacom_intern_2026',
      title: 'Datacom Intern Programme',
      organization: 'Datacom',
      organizationUrl: 'https://datacom.com',
      description: 'Internship at Australasia\'s largest home-grown technology company. Work across cloud, software development, cybersecurity, or managed services, delivering IT solutions for government and enterprise clients.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'technology', 'cloud', 'software', 'cybersecurity', 'managed-services'],
      skills: ['software-development', 'cloud-computing', 'cybersecurity', 'agile'],
      industries: ['Technology', 'IT Services', 'Cloud'],
      category: 'Internships',
      url: 'https://datacom.com/nz/en/careers/graduates',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Technology, cloud, and software streams. Auckland and Wellington offices.',
      },
      benefits: ['NZ tech leader', 'Government/enterprise clients', 'Mentorship', 'Graduate pathway'],
    },
    {
      id: 'intern_mercury_energy_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'mercury_summer_2026',
      title: 'Mercury Energy Summer Intern',
      organization: 'Mercury NZ',
      organizationUrl: 'https://www.mercury.co.nz',
      description: 'Summer internship at Mercury, one of NZ\'s largest electricity generators and retailers. Gain experience in energy, engineering, digital, or corporate teams while contributing to New Zealand\'s renewable energy future.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'energy', 'renewable', 'engineering', 'digital', 'summer'],
      skills: ['engineering', 'data-analysis', 'problem-solving', 'sustainability'],
      industries: ['Energy', 'Utilities', 'Renewable Energy'],
      category: 'Internships',
      url: 'https://www.mercury.co.nz/about-us/careers/summer-interns',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      dates: { startDate: '2026-11-01', endDate: '2027-02-28' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid summer internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Energy, engineering, and digital streams. Auckland and Hamilton.',
      },
      benefits: ['Renewable energy focus', 'Sustainability impact', 'Mentorship', 'Graduate pathway'],
    },
    {
      id: 'intern_aurecon_nz_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'aurecon_summer_2026',
      title: 'Aurecon NZ Summer Intern',
      organization: 'Aurecon',
      organizationUrl: 'https://www.aurecongroup.com',
      description: 'Summer internship at Aurecon, a global engineering and infrastructure advisory firm. Work on transformative projects in transport, water, buildings, and energy alongside a diverse team of engineers and advisors.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'engineering', 'infrastructure', 'advisory', 'transport', 'summer'],
      skills: ['engineering', 'design-thinking', 'project-management', 'teamwork'],
      industries: ['Engineering', 'Infrastructure', 'Advisory'],
      category: 'Internships',
      url: 'https://www.aurecongroup.com/careers/graduates-and-interns',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 9 * day).toISOString(),
      dates: { startDate: '2026-11-01', endDate: '2027-02-28' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid summer internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Engineering and infrastructure streams. Auckland and Wellington offices.',
      },
      benefits: ['Global engineering firm', 'Diverse projects', 'Mentorship', 'Graduate pathway'],
    },
    {
      id: 'intern_spark_nz_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'spark_nz_intern_2026',
      title: 'Spark NZ Technology Intern',
      organization: 'Spark New Zealand',
      organizationUrl: 'https://www.spark.co.nz',
      description: 'Technology internship at NZ\'s largest telecommunications company. Work on digital, network, data, or software projects powering connections for millions of New Zealanders across the country.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'telecommunications', 'technology', 'digital', 'network'],
      skills: ['software-development', 'data-analysis', 'networking', 'agile'],
      industries: ['Telecommunications', 'Technology', 'Digital'],
      category: 'Internships',
      url: 'https://www.spark.co.nz/careers/students-graduates/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 5 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Technology and digital streams. Auckland and Wellington offices.',
      },
      benefits: ['NZ telco leader', 'Digital transformation', 'Mentorship', 'Graduate pathway'],
    },
    {
      id: 'intern_bnz_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'bnz_intern_2026',
      title: 'BNZ Intern Programme',
      organization: 'Bank of New Zealand',
      organizationUrl: 'https://www.bnz.co.nz',
      description: 'Internship at one of NZ\'s oldest and largest banks. Gain experience in banking, technology, analytics, or risk while working on real projects that impact BNZ\'s two million customers.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'banking', 'technology', 'analytics', 'finance'],
      skills: ['financial-analysis', 'data-analysis', 'communication', 'problem-solving'],
      industries: ['Banking', 'Finance', 'Technology'],
      category: 'Internships',
      url: 'https://careers.bnz.co.nz/graduates',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 7 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Banking, technology, and analytics streams. Auckland and Wellington offices.',
      },
      benefits: ['Major NZ bank', 'Cross-functional exposure', 'Mentorship', 'Graduate pathway'],
    },
    {
      id: 'intern_asb_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'asb_summer_2026',
      title: 'ASB Summer Intern',
      organization: 'ASB Bank',
      organizationUrl: 'https://www.asb.co.nz',
      description: 'Summer internship at ASB, one of NZ\'s leading banks known for digital innovation. Work in banking, technology, or data teams at their Auckland North Wharf campus, shaping the future of digital banking.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'banking', 'technology', 'data', 'digital-innovation'],
      skills: ['data-analysis', 'software-development', 'communication', 'analytical-thinking'],
      industries: ['Banking', 'Finance', 'Technology'],
      category: 'Internships',
      url: 'https://www.asb.co.nz/careers/graduates-interns',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      dates: { startDate: '2026-11-01', endDate: '2027-02-28' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid summer internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Banking, technology, and data streams. Auckland-based.',
      },
      benefits: ['Digital banking leader', 'Modern campus', 'Mentorship', 'Graduate pathway'],
    },
    {
      id: 'intern_wsp_nz_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'wsp_nz_summer_2026',
      title: 'WSP NZ Summer Intern',
      organization: 'WSP in New Zealand',
      organizationUrl: 'https://www.wsp.com/en-nz',
      description: 'Summer internship at WSP, a global engineering and professional services firm. Work on infrastructure, transport, environment, and building projects that shape communities across New Zealand.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'engineering', 'environment', 'transport', 'infrastructure', 'summer'],
      skills: ['engineering', 'environmental-science', 'project-management', 'teamwork'],
      industries: ['Engineering', 'Environment', 'Transport', 'Infrastructure'],
      category: 'Internships',
      url: 'https://www.wsp.com/en-nz/careers/early-careers',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 10 * day).toISOString(),
      dates: { startDate: '2026-11-01', endDate: '2027-02-28' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid summer internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Engineering, environment, and transport streams. Multiple NZ cities.',
      },
      benefits: ['Global engineering firm', 'Community impact', 'Mentorship', 'Graduate pathway'],
    },
    {
      id: 'intern_tonkin_taylor_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'tonkin_taylor_intern_2026',
      title: 'Tonkin + Taylor Intern',
      organization: 'Tonkin + Taylor',
      organizationUrl: 'https://www.tonkintaylor.co.nz',
      description: 'Internship at NZ\'s leading environmental and engineering consultancy. Work on geotechnical, environmental, and infrastructure projects, gaining practical experience in earth and environmental sciences alongside expert practitioners.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'environmental-engineering', 'geoscience', 'geotechnical', 'infrastructure'],
      skills: ['environmental-science', 'geotechnical-engineering', 'data-analysis', 'fieldwork'],
      industries: ['Environmental', 'Engineering', 'Geoscience'],
      category: 'Internships',
      url: 'https://www.tonkintaylor.co.nz/careers/graduates-interns/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 8 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid internship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Environmental engineering and geoscience streams. Auckland, Wellington, and Christchurch.',
      },
      benefits: ['NZ environmental leader', 'Field experience', 'Mentorship', 'Graduate pathway'],
    },
    {
      id: 'intern_minterellison_clerk_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'minterellison_summer_clerk_2026',
      title: 'MinterEllisonRuddWatts Summer Clerk',
      organization: 'MinterEllisonRuddWatts',
      organizationUrl: 'https://www.minterellison.co.nz',
      description: 'Summer clerkship at one of New Zealand\'s leading commercial law firms. Gain real legal experience working alongside partners and senior associates across corporate, litigation, banking, and property law teams.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'law', 'legal', 'commercial-law', 'summer-clerk'],
      skills: ['legal-research', 'analytical-thinking', 'written-communication', 'attention-to-detail'],
      industries: ['Legal', 'Professional Services'],
      category: 'Internships',
      url: 'https://www.minterellison.co.nz/careers/summer-clerks',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 2 * day).toISOString(),
      dates: { startDate: '2026-11-01', endDate: '2027-02-15' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid summer clerkship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        degrees: ['Law', 'LLB'],
        note: 'Penultimate year law students. Auckland and Wellington offices.',
      },
      benefits: ['Top-tier law firm', 'Client exposure', 'Mentorship', 'Graduate pathway'],
    },
    {
      id: 'intern_russell_mcveagh_clerk_2026',
      type: 'internship',
      source: 'curated',
      sourceId: 'russell_mcveagh_clerk_2026',
      title: 'Russell McVeagh Summer Clerk',
      organization: 'Russell McVeagh',
      organizationUrl: 'https://russellmcveagh.com',
      description: 'Summer clerkship at one of New Zealand\'s most prestigious law firms. Work on high-profile transactions, disputes, and regulatory matters alongside leading lawyers in a firm known for NZ\'s largest and most complex legal work.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['internship', 'law', 'legal', 'commercial-law', 'summer-clerk', 'top-tier'],
      skills: ['legal-research', 'analytical-thinking', 'written-communication', 'attention-to-detail'],
      industries: ['Legal', 'Professional Services'],
      category: 'Internships',
      url: 'https://russellmcveagh.com/careers/summer-clerks',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 1 * day).toISOString(),
      dates: { startDate: '2026-11-01', endDate: '2027-02-15' },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid summer clerkship' },
      eligibility: {
        studyLevel: ['Undergraduate'],
        degrees: ['Law', 'LLB'],
        note: 'Penultimate year law students. Auckland and Wellington offices.',
      },
      benefits: ['NZ\'s top-tier firm', 'High-profile work', 'Mentorship', 'Graduate pathway'],
    },
  ];
}

export const internshipsConnector: OpportunityConnector = {
  name: 'internships',
  supportedTypes: ['internship'],
  async fetch(config): Promise<ConnectorResult> {
    const errors: string[] = [];
    let opportunities: Opportunity[] = [];

    try {
      const gradNZ = await fetchGradNZInternships();
      opportunities.push(...gradNZ);
      console.log(`[InternshipsConnector] Scraped ${gradNZ.length} from GradNewZealand`);
    } catch (err) {
      errors.push(`GradNZ: ${String(err)}`);
    }

    try {
      const prosple = await fetchProspleNZInternships();
      opportunities.push(...prosple);
      console.log(`[InternshipsConnector] Scraped ${prosple.length} from Prosple NZ`);
    } catch (err) {
      errors.push(`Prosple: ${String(err)}`);
    }

    opportunities.push(...getCuratedInternships());

    if (config.maxResults) {
      opportunities = opportunities.slice(0, config.maxResults);
    }

    return {
      opportunities,
      source: 'internships',
      fetchedAt: new Date().toISOString(),
      stats: { fetched: opportunities.length, validated: opportunities.length, errors },
    };
  },
};
