import { Opportunity } from '@/types/opportunities';
import { OpportunityConnector, ConnectorConfig, ConnectorResult } from './types';
import * as cheerio from 'cheerio';

async function fetchUoAScholarships(): Promise<Opportunity[]> {
  try {
    const res = await fetch(
      'https://www.auckland.ac.nz/en/study/scholarships-and-awards/scholarship-types/undergraduate-scholarships.html',
      { headers: { 'User-Agent': 'Gradual-App/2.0', Accept: 'text/html' } }
    );
    if (!res.ok) return [];
    const html = await res.text();
    const $ = cheerio.load(html);
    const scholarships: Opportunity[] = [];

    $('a[href*="scholarships-and-awards"]').each((_i, el) => {
      const title = $(el).text().trim();
      const href = $(el).attr('href') || '';
      if (!title || title.length < 10 || title.length > 200) return;
      if (['Find a scholarship', 'Scholarship types', 'How to apply', 'Search', 'Browse'].some(s => title.includes(s))) return;

      const fullUrl = href.startsWith('http') ? href : `https://www.auckland.ac.nz${href}`;

      scholarships.push({
        id: `uoa_schol_${title.toLowerCase().replace(/[^a-z0-9]/g, '_').slice(0, 60)}`,
        type: 'scholarship',
        source: 'uoa',
        sourceId: href,
        sourceUrl: fullUrl,
        title,
        organization: 'University of Auckland',
        organizationUrl: 'https://www.auckland.ac.nz',
        description: `${title} — a scholarship available at the University of Auckland. Check eligibility and application deadlines on the university website.`,
        location: 'Auckland, New Zealand',
        locationType: 'onsite',
        city: 'Auckland',
        country: 'New Zealand',
        tags: ['scholarship', 'university', 'auckland', 'financial-support'],
        category: 'Scholarships',
        url: fullUrl,
        applicationType: 'external',
        status: 'active',
        createdAt: new Date().toISOString(),
      });
    });
    return scholarships;
  } catch (err) {
    console.error('[ScholarshipsConnector] UoA scrape failed:', err);
    return [];
  }
}

function getCuratedScholarships(): Opportunity[] {
  const now = Date.now();
  const day = 24 * 60 * 60 * 1000;
  return [
    {
      id: 'schol_uoa_top_achiever',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'uoa_top_achiever',
      title: 'University of Auckland Top Achiever Scholarship',
      organization: 'University of Auckland',
      organizationUrl: 'https://www.auckland.ac.nz',
      description: 'For exceptional students with excellent academic achievement and leadership potential. Includes one year of catered accommodation at a University of Auckland Hall of Residence plus $5,000 paid over two semesters.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['scholarship', 'academic-excellence', 'leadership', 'accommodation', 'university'],
      skills: ['academic-achievement', 'leadership'],
      industries: ['Education'],
      category: 'Scholarships',
      url: 'https://auckland.ac.nz/en/study/scholarships-and-awards/scholarship-types/undergraduate-scholarships/entry-level-and-first-year-scholarships/top-achiever-scholarships.html',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 5 * day).toISOString(),
      compensation: {
        type: 'paid',
        currency: 'NZD',
        description: 'Catered accommodation + $5,000',
      },
      eligibility: {
        citizenship: ['NZ citizen', 'NZ permanent resident'],
        studyLevel: ['Undergraduate'],
        note: 'Final year secondary school or gap year students intending to enrol full-time',
      },
      benefits: ['Accommodation', '$5,000 stipend', 'Academic community'],
    },
    {
      id: 'schol_uc_eamon_molloy',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'uc_eamon_molloy',
      title: 'Eamon Molloy Memorial Scholarship',
      organization: 'University of Canterbury',
      organizationUrl: 'https://www.canterbury.ac.nz',
      description: 'Worth $7,500 for Asian students in their 2nd to 4th year at UC. Supports students demonstrating academic achievement and community involvement. Applications close 31 March.',
      location: 'Christchurch, New Zealand',
      locationType: 'onsite',
      city: 'Christchurch',
      country: 'New Zealand',
      tags: ['scholarship', 'asian-students', 'undergraduate', 'university'],
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Asian students in 2nd-4th year at UC',
      },
      category: 'Scholarships',
      url: 'https://www.canterbury.ac.nz/study/getting-started/scholarships/undergraduate-scholarships/general-undergraduate-scholarships',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 8 * day).toISOString(),
      deadline: new Date(now + 60 * day).toISOString(),
      dates: { deadline: new Date(now + 60 * day).toISOString() },
      compensation: { type: 'paid', currency: 'NZD', amount: 7500, description: '$7,500 scholarship' },
    },
    {
      id: 'schol_uc_russell_smith',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'uc_russell_smith',
      title: 'Dr Russell Smith Memorial Scholarship',
      organization: 'University of Canterbury',
      organizationUrl: 'https://www.canterbury.ac.nz',
      description: 'Worth $2,000 for students with vision impairment studying at UC. Supports accessibility and inclusion in higher education. Applications close 31 March.',
      location: 'Christchurch, New Zealand',
      locationType: 'onsite',
      city: 'Christchurch',
      country: 'New Zealand',
      tags: ['scholarship', 'accessibility', 'disability', 'undergraduate'],
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Students with vision impairment at UC',
      },
      category: 'Scholarships',
      url: 'https://www.canterbury.ac.nz/study/getting-started/scholarships/undergraduate-scholarships/general-undergraduate-scholarships',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 7 * day).toISOString(),
      deadline: new Date(now + 60 * day).toISOString(),
      dates: { deadline: new Date(now + 60 * day).toISOString() },
      compensation: { type: 'paid', currency: 'NZD', amount: 2000, description: '$2,000 scholarship' },
    },
    {
      id: 'schol_uc_ah_nua',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'uc_ah_nua',
      title: 'Ah Nua Scholarship',
      organization: 'University of Canterbury',
      organizationUrl: 'https://www.canterbury.ac.nz',
      description: 'Up to $5,000 for Asian and Pacific international students in their 3rd or 4th year experiencing financial hardship. Supporting diverse students at UC.',
      location: 'Christchurch, New Zealand',
      locationType: 'onsite',
      city: 'Christchurch',
      country: 'New Zealand',
      tags: ['scholarship', 'international', 'pacific', 'asian', 'financial-support'],
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Asian and Pacific international students in 3rd/4th year experiencing hardship',
      },
      category: 'Scholarships',
      url: 'https://www.canterbury.ac.nz/study/getting-started/scholarships/undergraduate-scholarships/general-undergraduate-scholarships',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Up to $5,000' },
    },
    {
      id: 'schol_uc_summer_research',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'uc_summer_2026',
      title: 'UC Summer Research Scholarships 2026',
      organization: 'University of Canterbury',
      organizationUrl: 'https://www.canterbury.ac.nz',
      description: 'Paid summer research positions working with UC academics. Gain real research experience in your field, build academic connections, and develop your research skills over the university break.',
      location: 'Christchurch, New Zealand',
      locationType: 'onsite',
      city: 'Christchurch',
      country: 'New Zealand',
      tags: ['scholarship', 'research', 'summer', 'academic', 'paid'],
      skills: ['research', 'academic-writing', 'data-analysis'],
      category: 'Scholarships',
      url: 'https://www.canterbury.ac.nz/news-and-events/student-notices/2026/summer-scholarships-application-round-is-now-open',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 2 * day).toISOString(),
      deadline: new Date(now + 30 * day).toISOString(),
      dates: { deadline: new Date(now + 30 * day).toISOString() },
      compensation: { type: 'paid', currency: 'NZD', description: 'Paid research position' },
      benefits: ['Paid position', 'Research experience', 'Academic mentorship'],
    },
    {
      id: 'schol_uc_ada_wells',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'uc_ada_wells',
      title: 'Ada Wells Memorial Prize',
      organization: 'University of Canterbury',
      organizationUrl: 'https://www.canterbury.ac.nz',
      description: '$1,000 essay prize at the University of Canterbury. Open to undergraduate students — demonstrate your writing and analytical skills for a chance to win.',
      location: 'Christchurch, New Zealand',
      locationType: 'onsite',
      city: 'Christchurch',
      country: 'New Zealand',
      tags: ['scholarship', 'essay', 'writing', 'prize', 'academic'],
      skills: ['academic-writing', 'critical-thinking'],
      category: 'Scholarships',
      url: 'https://www.canterbury.ac.nz/study/getting-started/scholarships/undergraduate-scholarships/general-undergraduate-scholarships',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 9 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', amount: 1000, description: '$1,000 prize' },
    },
    {
      id: 'schol_nz_pm_scholarship',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'nz_pm_scholarship',
      title: 'Prime Minister\'s Scholarship for Asia (PMSA)',
      organization: 'Education New Zealand',
      organizationUrl: 'https://enz.govt.nz',
      description: 'Funding for NZ students to study, research, or intern in Asia. Group awards up to $3,000 per student, Individual awards up to $14,000. Build international experience and cultural understanding.',
      location: 'Asia (from New Zealand)',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['scholarship', 'international', 'asia', 'study-abroad', 'government'],
      skills: ['cultural-awareness', 'research', 'international-experience'],
      eligibility: {
        citizenship: ['NZ citizen', 'NZ permanent resident'],
        studyLevel: ['Undergraduate', 'Postgraduate'],
        note: 'Must be enrolled at a NZ institution',
      },
      category: 'Scholarships',
      url: 'https://enz.govt.nz/funding/prime-ministers-scholarship-for-asia',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 10 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Up to $14,000 individual, $3,000 group' },
      benefits: ['Travel funding', 'Study abroad', 'Cultural immersion'],
    },
    {
      id: 'schol_aut_scholarship',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'aut_equity_2026',
      title: 'AUT Equity Scholarships',
      organization: 'Auckland University of Technology',
      organizationUrl: 'https://www.aut.ac.nz',
      description: 'AUT offers a range of equity scholarships supporting Māori, Pacific, disabled students, sole parents, and those experiencing financial hardship. Multiple awards available across all faculties.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['scholarship', 'equity', 'maori', 'pacific', 'disability', 'financial-support'],
      eligibility: {
        studyLevel: ['Undergraduate', 'Postgraduate'],
        note: 'Various equity criteria — Māori, Pacific, disabled, sole parents, financial hardship',
      },
      category: 'Scholarships',
      url: 'https://www.aut.ac.nz/study/fees-and-scholarships/scholarships',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Various amounts' },
    },
    {
      id: 'schol_massey_toroa_intl',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'massey_toroa_intl',
      title: 'Massey University Toroa International Undergraduate Fee Scholarship',
      organization: 'Massey University',
      organizationUrl: 'https://www.massey.ac.nz',
      description: 'NZ$5,000 fee scholarship for international undergraduate students starting at Massey University. Up to 85 awards available for Semester 2 (July 2026). Applications open 15 February to 15 April 2026.',
      location: 'Palmerston North, New Zealand',
      locationType: 'onsite',
      city: 'Palmerston North',
      country: 'New Zealand',
      tags: ['scholarship', 'international', 'undergraduate', 'university', 'massey'],
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'International students commencing undergraduate study at Massey',
      },
      category: 'Scholarships',
      url: 'https://www.massey.ac.nz/study/scholarships-and-awards/toroa-international-undergraduate-fee-scholarships/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      deadline: '2026-04-15T23:59:59.000Z',
      dates: { deadline: '2026-04-15T23:59:59.000Z' },
      compensation: { type: 'paid', currency: 'NZD', amount: 5000, description: 'NZ$5,000 fee scholarship' },
    },
    {
      id: 'schol_waikato_vc_intl_excellence',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'waikato_vc_intl_excellence',
      title: "University of Waikato Vice Chancellor's International Excellence Scholarship",
      organization: 'University of Waikato',
      organizationUrl: 'https://www.waikato.ac.nz',
      description: "Up to NZD$15,000 for high-achieving international students at the University of Waikato. Available for both undergraduate and postgraduate study. Rolling monthly application rounds throughout the year.",
      location: 'Hamilton, New Zealand',
      locationType: 'onsite',
      city: 'Hamilton',
      country: 'New Zealand',
      tags: ['scholarship', 'international', 'academic-excellence', 'undergraduate', 'postgraduate', 'university'],
      eligibility: {
        studyLevel: ['Undergraduate', 'Postgraduate'],
        note: 'International students with strong academic records; rolling monthly applications',
      },
      category: 'Scholarships',
      url: 'https://www.waikato.ac.nz/study/scholarships/find-a-scholarship/vice-chancellors-international-excellence-scholarship/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Up to NZD$15,000' },
    },
    {
      id: 'schol_otago_vc_intl_postgrad',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'otago_vc_intl_postgrad',
      title: "University of Otago Vice-Chancellor's International Postgraduate Scholarship",
      organization: 'University of Otago',
      organizationUrl: 'https://www.otago.ac.nz',
      description: "NZ$10,000 scholarship for international students undertaking Masters coursework or Postgraduate Diploma programmes at the University of Otago. Awarded for up to 12 months of study.",
      location: 'Dunedin, New Zealand',
      locationType: 'onsite',
      city: 'Dunedin',
      country: 'New Zealand',
      tags: ['scholarship', 'international', 'postgraduate', 'masters', 'university'],
      eligibility: {
        studyLevel: ['Postgraduate'],
        note: 'International students enrolled in Masters coursework or PGDip at Otago',
      },
      category: 'Scholarships',
      url: 'https://www.otago.ac.nz/courses/scholarships/vice-chancellors-international-postgraduate-scholarships',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 7 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', amount: 10000, description: 'NZ$10,000 for up to 12 months' },
    },
    {
      id: 'schol_vic_tangiwai_excellence',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'vic_tangiwai_excellence',
      title: 'Victoria University Tangiwai Excellence Scholarship',
      organization: 'Victoria University of Wellington',
      organizationUrl: 'https://www.victoria.ac.nz',
      description: 'School leaver excellence scholarship at Victoria University of Wellington. Recognises outstanding academic achievement and leadership in Year 13 students transitioning to undergraduate study.',
      location: 'Wellington, New Zealand',
      locationType: 'onsite',
      city: 'Wellington',
      country: 'New Zealand',
      tags: ['scholarship', 'school-leaver', 'academic-excellence', 'undergraduate', 'university'],
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Year 13 school leavers with excellent academic records',
      },
      category: 'Scholarships',
      url: 'https://www.victoria.ac.nz/scholarships/current/victoria-tangiwai-scholarship-school-leaver-scholarships-for-excellence',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 11 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Excellence scholarship — check website for value' },
    },
    {
      id: 'schol_manaaki_nz_otago',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'manaaki_nz_otago',
      title: 'Manaaki New Zealand Scholarships (Otago)',
      organization: 'University of Otago / NZ Government',
      organizationUrl: 'https://www.otago.ac.nz',
      description: 'Fully funded New Zealand Government scholarships for students from eligible developing countries. Covers tuition fees, return airfares, medical and travel insurance, and a living allowance. Study at the University of Otago.',
      location: 'Dunedin, New Zealand',
      locationType: 'onsite',
      city: 'Dunedin',
      country: 'New Zealand',
      tags: ['scholarship', 'government', 'international', 'fully-funded', 'postgraduate'],
      eligibility: {
        studyLevel: ['Undergraduate', 'Postgraduate'],
        note: 'Students from eligible developing countries; NZ Government-funded',
      },
      category: 'Scholarships',
      url: 'https://www.otago.ac.nz/international/future-students/fees-scholarships/international-scholarships/manaaki-scholarships',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 12 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Full scholarship — tuition, airfares, insurance, living costs' },
      benefits: ['Full tuition', 'Return airfares', 'Medical & travel insurance', 'Living allowance'],
    },
    {
      id: 'schol_uoa_engineering',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'uoa_engineering',
      title: 'UoA Faculty of Engineering Scholarship',
      organization: 'University of Auckland',
      organizationUrl: 'https://www.auckland.ac.nz',
      description: 'Scholarship for high-achieving students in the Faculty of Engineering at the University of Auckland. Supports students demonstrating academic excellence and potential to contribute to the engineering profession.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['scholarship', 'engineering', 'academic-excellence', 'university', 'STEM'],
      skills: ['engineering', 'problem-solving'],
      industries: ['Engineering', 'Technology'],
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'High-achieving engineering students at UoA',
      },
      category: 'Scholarships',
      url: 'https://www.auckland.ac.nz/en/study/scholarships-and-awards.html',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 5 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Scholarship — check website for value' },
    },
    {
      id: 'schol_uoa_maori_excellence',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'uoa_maori_excellence',
      title: 'UoA Māori Academic Excellence Scholarship',
      organization: 'University of Auckland',
      organizationUrl: 'https://www.auckland.ac.nz',
      description: 'Supporting Māori student success at the University of Auckland. Awarded to Māori students who demonstrate academic excellence and the potential to be future leaders in their communities and professions.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['scholarship', 'maori', 'academic-excellence', 'equity', 'university'],
      eligibility: {
        studyLevel: ['Undergraduate', 'Postgraduate'],
        note: 'Māori students demonstrating academic excellence',
      },
      category: 'Scholarships',
      url: 'https://www.auckland.ac.nz/en/study/scholarships-and-awards.html',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Scholarship — check website for value' },
    },
    {
      id: 'schol_uoa_pacific_excellence',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'uoa_pacific_excellence',
      title: 'UoA Pacific Academic Excellence Scholarship',
      organization: 'University of Auckland',
      organizationUrl: 'https://www.auckland.ac.nz',
      description: 'Supporting Pacific student success at the University of Auckland. Recognises Pacific students with strong academic records and a commitment to contributing to their Pacific communities.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['scholarship', 'pacific', 'academic-excellence', 'equity', 'university'],
      eligibility: {
        studyLevel: ['Undergraduate', 'Postgraduate'],
        note: 'Pacific students demonstrating academic excellence',
      },
      category: 'Scholarships',
      url: 'https://www.auckland.ac.nz/en/study/scholarships-and-awards.html',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Scholarship — check website for value' },
    },
    {
      id: 'schol_uc_emerging_leaders',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'uc_emerging_leaders',
      title: 'University of Canterbury Emerging Leaders Scholarship',
      organization: 'University of Canterbury',
      organizationUrl: 'https://www.canterbury.ac.nz',
      description: 'For students demonstrating outstanding leadership potential alongside academic achievement. Supports emerging leaders entering study at the University of Canterbury.',
      location: 'Christchurch, New Zealand',
      locationType: 'onsite',
      city: 'Christchurch',
      country: 'New Zealand',
      tags: ['scholarship', 'leadership', 'undergraduate', 'university'],
      skills: ['leadership', 'community-engagement'],
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Students demonstrating leadership potential',
      },
      category: 'Scholarships',
      url: 'https://www.canterbury.ac.nz/study/getting-started/scholarships/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 8 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Scholarship — check website for value' },
    },
    {
      id: 'schol_aut_vc_doctoral',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'aut_vc_doctoral',
      title: "AUT Vice Chancellor's Doctoral Scholarship",
      organization: 'Auckland University of Technology',
      organizationUrl: 'https://www.aut.ac.nz',
      description: "Funding for doctoral research at AUT. Supports outstanding candidates undertaking a Doctor of Philosophy (PhD) at Auckland University of Technology with a stipend and tuition fee waiver.",
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['scholarship', 'doctoral', 'PhD', 'research', 'university'],
      skills: ['research', 'academic-writing', 'critical-thinking'],
      eligibility: {
        studyLevel: ['Doctoral'],
        note: 'Candidates accepted into a PhD programme at AUT',
      },
      category: 'Scholarships',
      url: 'https://www.aut.ac.nz/study/fees-and-scholarships/scholarships',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Stipend + tuition fee waiver' },
      benefits: ['Stipend', 'Tuition fee waiver', 'Research support'],
    },
    {
      id: 'schol_callaghan_rd_career',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'callaghan_rd_career',
      title: 'Callaghan Innovation R&D Career Grant',
      organization: 'Callaghan Innovation',
      organizationUrl: 'https://www.callaghaninnovation.govt.nz',
      description: 'Up to $9,000 for STEM students doing research placements with NZ companies. Gain hands-on R&D experience while contributing to real innovation projects in New Zealand businesses.',
      location: 'New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['scholarship', 'STEM', 'research', 'industry', 'government', 'R&D'],
      skills: ['research', 'STEM', 'data-analysis', 'problem-solving'],
      industries: ['Science', 'Technology', 'Engineering'],
      eligibility: {
        studyLevel: ['Undergraduate', 'Postgraduate'],
        note: 'STEM students undertaking research placements with NZ businesses',
      },
      category: 'Scholarships',
      url: 'https://www.callaghaninnovation.govt.nz/grants/r-d-career-grants',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 13 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', amount: 9000, description: 'Up to $9,000' },
      benefits: ['Industry experience', 'R&D skills', 'Professional network'],
    },
    {
      id: 'schol_engineering_nz_futureintech',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'engineering_nz_futureintech',
      title: 'Engineering NZ Futureintech Scholarship',
      organization: 'Engineering New Zealand',
      organizationUrl: 'https://www.engineeringnz.org',
      description: 'Scholarship for engineering students in New Zealand, administered through the Futureintech programme. Supports aspiring engineers to complete their qualifications and enter the profession.',
      location: 'New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['scholarship', 'engineering', 'STEM', 'professional-development'],
      skills: ['engineering', 'problem-solving', 'technical-skills'],
      industries: ['Engineering'],
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'Engineering students at NZ tertiary institutions',
      },
      category: 'Scholarships',
      url: 'https://www.engineeringnz.org/programmes/futureintech/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 14 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Scholarship — check website for value' },
    },
    {
      id: 'schol_nzma_medical',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'nzma_medical',
      title: 'NZMA Scholarship for Medical Students',
      organization: 'New Zealand Medical Association',
      organizationUrl: 'https://www.nzma.org.nz',
      description: 'Scholarship supporting medical students in New Zealand. Assists students pursuing medical degrees and aims to strengthen the future medical workforce across the country.',
      location: 'New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['scholarship', 'medical', 'health', 'university'],
      skills: ['medical-knowledge', 'clinical-skills'],
      industries: ['Health', 'Medicine'],
      eligibility: {
        studyLevel: ['Undergraduate', 'Postgraduate'],
        note: 'Medical students enrolled at NZ universities',
      },
      category: 'Scholarships',
      url: 'https://www.nzma.org.nz/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 15 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Scholarship — check website for value' },
    },
    {
      id: 'schol_nz_law_foundation',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'nz_law_foundation',
      title: 'NZ Law Foundation Scholarship',
      organization: 'New Zealand Law Foundation',
      organizationUrl: 'https://www.nzlawfoundation.org.nz',
      description: 'Supporting law students in New Zealand through the NZ Law Foundation. Aimed at students demonstrating academic excellence and a commitment to the legal profession and access to justice.',
      location: 'New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['scholarship', 'law', 'legal', 'university'],
      skills: ['legal-research', 'critical-thinking', 'academic-writing'],
      industries: ['Law', 'Legal Services'],
      eligibility: {
        studyLevel: ['Undergraduate', 'Postgraduate'],
        note: 'Law students at NZ universities',
      },
      category: 'Scholarships',
      url: 'https://www.nzlawfoundation.org.nz/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 16 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Scholarship — check website for value' },
    },
    {
      id: 'schol_todd_foundation',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'todd_foundation',
      title: 'Todd Foundation Scholarship',
      organization: 'Todd Foundation',
      organizationUrl: 'https://toddfoundation.org.nz',
      description: 'Significant funding for students in energy, science, and engineering fields. The Todd Foundation supports postgraduate students whose research contributes to New Zealand\'s energy and innovation landscape.',
      location: 'New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['scholarship', 'energy', 'science', 'engineering', 'postgraduate', 'research'],
      skills: ['research', 'engineering', 'science'],
      industries: ['Energy', 'Science', 'Engineering'],
      eligibility: {
        studyLevel: ['Postgraduate'],
        note: 'Students in energy, science, or engineering fields',
      },
      category: 'Scholarships',
      url: 'https://toddfoundation.org.nz/what-we-do/scholarships/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 10 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Significant funding — check website for value' },
      benefits: ['Research funding', 'Professional network', 'Industry connections'],
    },
    {
      id: 'schol_ngarimu_vc_28_battalion',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'ngarimu_vc_28_battalion',
      title: 'Ngarimu VC and 28th (Māori) Battalion Memorial Scholarship',
      organization: 'Te Puni Kōkiri',
      organizationUrl: 'https://www.tpk.govt.nz',
      description: 'Up to $10,000 for Māori students in tertiary education. Honouring the legacy of the 28th Māori Battalion, this scholarship supports Māori learners committed to academic achievement and community leadership.',
      location: 'New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['scholarship', 'maori', 'government', 'tertiary', 'leadership'],
      eligibility: {
        citizenship: ['NZ citizen', 'NZ permanent resident'],
        studyLevel: ['Undergraduate', 'Postgraduate'],
        note: 'Māori students in tertiary education',
      },
      category: 'Scholarships',
      url: 'https://www.tpk.govt.nz/en/nga-putea-me-nga-ratonga/scholarships-for-maori/ngarimu-vc',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 9 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', amount: 10000, description: 'Up to $10,000' },
    },
    {
      id: 'schol_enz_study_abroad',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'enz_study_abroad',
      title: 'Education NZ Study Abroad Scholarship',
      organization: 'Education New Zealand',
      organizationUrl: 'https://enz.govt.nz',
      description: 'Funding for outbound NZ students looking to gain international study experience. Supports New Zealanders studying at partner institutions overseas to develop global perspectives and skills.',
      location: 'International (from New Zealand)',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['scholarship', 'study-abroad', 'international', 'government'],
      skills: ['cultural-awareness', 'international-experience'],
      eligibility: {
        citizenship: ['NZ citizen', 'NZ permanent resident'],
        studyLevel: ['Undergraduate', 'Postgraduate'],
        note: 'NZ students studying abroad at approved partner institutions',
      },
      category: 'Scholarships',
      url: 'https://enz.govt.nz/funding/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 11 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Funding support — check website for value' },
      benefits: ['International experience', 'Travel funding'],
    },
    {
      id: 'schol_google_nz',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'google_nz',
      title: 'Google NZ Scholarship',
      organization: 'Google',
      organizationUrl: 'https://www.google.com',
      description: 'Scholarship for computer science and technology students in New Zealand. Google supports students from underrepresented groups in tech who demonstrate academic excellence and leadership.',
      location: 'New Zealand',
      locationType: 'remote',
      country: 'New Zealand',
      tags: ['scholarship', 'technology', 'computer-science', 'diversity', 'STEM'],
      skills: ['programming', 'computer-science', 'software-engineering'],
      industries: ['Technology', 'Software'],
      eligibility: {
        studyLevel: ['Undergraduate', 'Postgraduate'],
        note: 'CS/tech students; check Google eligibility criteria',
      },
      category: 'Scholarships',
      url: 'https://buildyourfuture.withgoogle.com/scholarships',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 2 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Scholarship — check website for value' },
    },
    {
      id: 'schol_microsoft_apac',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'microsoft_apac',
      title: 'Microsoft APAC Scholarship',
      organization: 'Microsoft',
      organizationUrl: 'https://www.microsoft.com',
      description: 'Technology scholarship for students in the Asia-Pacific region, including New Zealand. Supports students pursuing degrees in computer science, engineering, and related STEM fields.',
      location: 'New Zealand / Asia-Pacific',
      locationType: 'remote',
      country: 'New Zealand',
      tags: ['scholarship', 'technology', 'STEM', 'computer-science', 'diversity'],
      skills: ['programming', 'software-engineering', 'technology'],
      industries: ['Technology', 'Software'],
      eligibility: {
        studyLevel: ['Undergraduate', 'Postgraduate'],
        note: 'Technology students in the APAC region',
      },
      category: 'Scholarships',
      url: 'https://www.microsoft.com/en-us/diversity/programs/scholarships',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 1 * day).toISOString(),
      compensation: { type: 'paid', currency: 'USD', description: 'Scholarship — check website for value' },
    },
    {
      id: 'schol_vodafone_nz_foundation',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'vodafone_nz_foundation',
      title: 'Vodafone NZ Foundation Scholarship',
      organization: 'Vodafone New Zealand Foundation',
      organizationUrl: 'https://www.vodafone.co.nz/foundation/',
      description: 'Supporting NZ youth in technology through the Vodafone NZ Foundation. Aimed at students passionate about using technology for social good and driving digital inclusion.',
      location: 'New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['scholarship', 'technology', 'social-impact', 'youth', 'digital-inclusion'],
      skills: ['technology', 'social-impact', 'digital-skills'],
      industries: ['Technology', 'Telecommunications'],
      eligibility: {
        studyLevel: ['Undergraduate'],
        note: 'NZ youth in technology fields',
      },
      category: 'Scholarships',
      url: 'https://www.vodafone.co.nz/foundation/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Scholarship — check website for value' },
    },
    {
      id: 'schol_nz_grad_women',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'nz_grad_women',
      title: 'NZ Federation of Graduate Women Scholarship',
      organization: 'NZ Federation of Graduate Women',
      organizationUrl: 'https://www.gwnz.org.nz',
      description: 'Scholarships for women in postgraduate study in New Zealand. Supports women pursuing masters and doctoral research across a range of disciplines, promoting women\'s participation in higher education.',
      location: 'New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['scholarship', 'women', 'postgraduate', 'equity', 'research'],
      eligibility: {
        studyLevel: ['Postgraduate', 'Doctoral'],
        note: 'Women in postgraduate study at NZ institutions',
      },
      category: 'Scholarships',
      url: 'https://www.gwnz.org.nz/scholarships',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 12 * day).toISOString(),
      compensation: { type: 'paid', currency: 'NZD', description: 'Scholarship — check website for value' },
    },
    {
      id: 'schol_fulbright_nz',
      type: 'scholarship',
      source: 'curated',
      sourceId: 'fulbright_nz',
      title: 'Fulbright NZ Scholarship',
      organization: 'Fulbright New Zealand',
      organizationUrl: 'https://www.fulbright.org.nz',
      description: 'Prestigious scholarship for New Zealand students and scholars to study, research, or teach in the United States. Covers tuition, living expenses, travel, and insurance for the duration of the award.',
      location: 'United States (from New Zealand)',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['scholarship', 'international', 'study-abroad', 'research', 'prestigious', 'USA'],
      skills: ['research', 'academic-writing', 'cultural-awareness'],
      eligibility: {
        citizenship: ['NZ citizen'],
        studyLevel: ['Postgraduate', 'Doctoral'],
        note: 'NZ citizens for study/research in the US',
      },
      category: 'Scholarships',
      url: 'https://www.fulbright.org.nz/awards/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 14 * day).toISOString(),
      compensation: { type: 'paid', currency: 'USD', description: 'Full funding — tuition, living expenses, travel, insurance' },
      benefits: ['Full tuition', 'Living expenses', 'Travel', 'Insurance', 'Fulbright network'],
    },
  ];
}

export const scholarshipsConnector: OpportunityConnector = {
  name: 'scholarships',
  supportedTypes: ['scholarship'],
  async fetch(config): Promise<ConnectorResult> {
    const errors: string[] = [];
    let opportunities: Opportunity[] = [];

    try {
      const live = await fetchUoAScholarships();
      opportunities.push(...live);
      console.log(`[ScholarshipsConnector] Scraped ${live.length} from UoA`);
    } catch (err) {
      errors.push(`UoA: ${String(err)}`);
    }

    opportunities.push(...getCuratedScholarships());

    if (config.maxResults) {
      opportunities = opportunities.slice(0, config.maxResults);
    }

    return {
      opportunities,
      source: 'scholarships',
      fetchedAt: new Date().toISOString(),
      stats: { fetched: opportunities.length, validated: opportunities.length, errors },
    };
  },
};
