import { Opportunity } from '@/types/opportunities';
import { OpportunityConnector, ConnectorConfig, ConnectorResult } from './types';
import * as cheerio from 'cheerio';

async function fetchSeekVolunteer(): Promise<Opportunity[]> {
  try {
    const res = await fetch('https://seekvolunteer.co.nz/volunteering?sort=newest', {
      headers: { 'User-Agent': 'Gradual-App/2.0', Accept: 'text/html' },
    });
    if (!res.ok) return [];
    const html = await res.text();
    const $ = cheerio.load(html);
    const opportunities: Opportunity[] = [];

    $('.search-results__item, .volunteer-card, article.listing, [class*="listing"], [class*="volunteer"]').each((_i, el) => {
      const $el = $(el);
      const title = $el.find('h2, h3, .title, .listing-title, a[class*="title"]').first().text().trim();
      const org = $el.find('.organisation, .company, .org-name, [class*="org"]').first().text().trim();
      const location = $el.find('.location, .suburb, [class*="location"]').first().text().trim();
      const link = $el.find('a[href*="/volunteering/"]').first().attr('href') || $el.find('a').first().attr('href') || '';
      const desc = $el.find('.description, .summary, p').first().text().trim();

      if (!title || !link || title.length < 3) return;
      const fullUrl = link.startsWith('http') ? link : `https://seekvolunteer.co.nz${link}`;

      opportunities.push({
        id: `seekvol_${link.replace(/[^a-z0-9]/gi, '_').slice(0, 60)}`,
        type: 'volunteering',
        source: 'seekvolunteer',
        sourceId: link,
        sourceUrl: fullUrl,
        canonicalUrl: fullUrl,
        title,
        organization: org || 'Seek Volunteer NZ',
        description: desc || title,
        location: location || 'New Zealand',
        locationType: 'onsite',
        city: location || undefined,
        country: 'New Zealand',
        tags: ['volunteering', 'community', 'new-zealand'],
        category: 'Volunteering',
        url: fullUrl,
        applicationType: 'external',
        status: 'active',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      });
    });
    return opportunities;
  } catch (err) {
    console.error('[VolunteeringConnector] Seek Volunteer fetch failed:', err);
    return [];
  }
}

function getCuratedVolunteering(): Opportunity[] {
  const now = Date.now();
  const day = 24 * 60 * 60 * 1000;
  return [
    {
      id: 'vol_uoa_sva',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'uoa_sva',
      title: 'University of Auckland Student Volunteer Army',
      organization: 'Student Volunteer Army (SVA)',
      organizationUrl: 'https://sva.org.nz',
      description: 'NZ\'s largest student-led volunteer movement, active at UoA. Respond to community needs, coordinate campus clean-ups, disaster relief logistics, and lead service projects across Auckland. Build leadership and project management skills.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['volunteering', 'community', 'leadership', 'disaster-response', 'student'],
      skills: ['leadership', 'teamwork', 'project-management', 'communication'],
      category: 'Community Service',
      url: 'https://sva.org.nz/volunteer/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      benefits: ['Leadership training', 'Reference letters', 'Networking', 'CV experience'],
    },
    {
      id: 'vol_doc_conservation',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'doc_vol',
      title: 'Department of Conservation (DOC) Volunteer',
      organization: 'Department of Conservation',
      organizationUrl: 'https://www.doc.govt.nz',
      description: 'Protect NZ\'s unique wildlife and natural heritage. Activities include predator trapping, track maintenance, tree planting, wildlife monitoring, and hut maintenance across national parks. Includes Hauturu-o-Toi/Little Barrier Island 17-18 day volunteer trips.',
      location: 'Multiple locations, New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['volunteering', 'conservation', 'environment', 'wildlife', 'outdoors'],
      skills: ['environmental-science', 'fieldwork', 'teamwork'],
      category: 'Conservation',
      url: 'https://www.doc.govt.nz/get-involved/volunteer/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 5 * day).toISOString(),
      benefits: ['Outdoor experience', 'Environmental impact', 'Training provided', 'Accommodation on trips'],
    },
    {
      id: 'vol_un_youth_nz',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'un_youth_vol',
      title: 'UN Youth NZ - Event Volunteer',
      organization: 'UN Youth New Zealand',
      organizationUrl: 'https://www.unyouth.org.nz',
      description: 'Volunteer at Auckland Model United Nations 2026 and other UN Youth events. Roles include Committee Facilitator, Logistics Officer, and Welfare Officer. Develop public speaking, diplomacy, and event management skills.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['volunteering', 'united-nations', 'diplomacy', 'leadership', 'events'],
      skills: ['public-speaking', 'diplomacy', 'event-management', 'leadership'],
      category: 'Leadership',
      url: 'https://www.unyouth.org.nz/volunteer-registrations/auckland-model-united-nations-2026---volunteer-applications',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      benefits: ['Leadership development', 'Event experience', 'Networking', 'Reference letters'],
    },
    {
      id: 'vol_youthline',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'youthline_vol',
      title: 'Youthline Helpline Volunteer',
      organization: 'Youthline',
      organizationUrl: 'https://www.youthline.co.nz',
      description: 'Provide free and confidential support to young people via phone, text, and online chat. Full training in counselling skills provided. Develop empathy, active listening, and crisis intervention abilities.',
      location: 'Auckland, New Zealand',
      locationType: 'hybrid',
      isRemote: true,
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['volunteering', 'mental-health', 'counselling', 'youth', 'helpline'],
      skills: ['communication', 'empathy', 'active-listening', 'crisis-intervention'],
      category: 'Mental Health',
      url: 'https://www.youthline.co.nz/volunteer-with-us.html',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      benefits: ['Counselling training', 'Flexible schedule', 'Meaningful impact'],
    },
    {
      id: 'vol_vic_kitea',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'vic_kitea',
      title: 'Kitea Impact Programme - Victoria University',
      organization: 'Victoria University of Wellington',
      organizationUrl: 'https://www.wgtn.ac.nz',
      description: 'Flexible volunteering programme at Vic. Volunteer with 300+ not-for-profit organisations in Wellington covering sustainability, community, education, and social justice. Recognised on your academic transcript.',
      location: 'Wellington, New Zealand',
      locationType: 'onsite',
      city: 'Wellington',
      country: 'New Zealand',
      tags: ['volunteering', 'community', 'sustainability', 'leadership', 'wellington'],
      skills: ['leadership', 'community-engagement', 'teamwork'],
      category: 'Community Service',
      url: 'https://www.wgtn.ac.nz/students/student-life/impact/wellington-plus/volunteer-in-the-community',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 8 * day).toISOString(),
      benefits: ['Transcript recognition', '300+ org partners', 'Flexible commitment'],
    },
    {
      id: 'vol_habitat_nz',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'habitat_nz',
      title: 'Habitat for Humanity NZ Build Volunteer',
      organization: 'Habitat for Humanity New Zealand',
      organizationUrl: 'https://habitat.org.nz',
      description: 'Help build affordable homes for families in need across New Zealand. No construction experience needed. Work as a team, learn practical skills, and make a tangible difference in your community.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['volunteering', 'construction', 'housing', 'community', 'hands-on'],
      skills: ['teamwork', 'construction', 'project-management'],
      category: 'Housing',
      url: 'https://habitat.org.nz/volunteer/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 10 * day).toISOString(),
      benefits: ['Practical skills', 'Community impact', 'Team experience'],
    },
    {
      id: 'vol_redcross_nz',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'redcross_nz',
      title: 'New Zealand Red Cross Community Volunteer',
      organization: 'New Zealand Red Cross',
      organizationUrl: 'https://www.redcross.org.nz',
      description: 'Support disaster response, refugee resettlement, community resilience, and first aid education. Flexible hours, comprehensive training. Roles across NZ helping vulnerable communities.',
      location: 'Multiple locations, New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['volunteering', 'humanitarian', 'disaster-response', 'refugee-support', 'first-aid'],
      skills: ['communication', 'first-aid', 'cultural-awareness', 'crisis-response'],
      category: 'Humanitarian',
      url: 'https://www.redcross.org.nz/get-involved/volunteer/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 7 * day).toISOString(),
      benefits: ['Training provided', 'Flexible hours', 'Global network', 'Reference letters'],
    },
    {
      id: 'vol_ousa_wellbeing',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'ousa_ayok',
      title: 'Are You OK? Wellbeing Team - Otago University',
      organization: 'Otago University Students\' Association (OUSA)',
      organizationUrl: 'https://volunteersouth.org.nz',
      description: 'Provide safety and wellbeing support at campus events at Otago Uni. Trained in first aid, bystander intervention, and emotional support. Perfect for health, psychology, or social work students.',
      location: 'Dunedin, New Zealand',
      locationType: 'onsite',
      city: 'Dunedin',
      country: 'New Zealand',
      tags: ['volunteering', 'wellbeing', 'first-aid', 'student', 'dunedin'],
      skills: ['first-aid', 'empathy', 'crisis-response', 'communication'],
      category: 'Student Welfare',
      url: 'https://volunteersouth.org.nz/roles/1532/are-you-ok-2025-team-ousa',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 2 * day).toISOString(),
      benefits: ['First aid training', 'Bystander intervention training', 'Leadership'],
    },
    {
      id: 'vol_cvnz_conservation',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'cvnz_conservation',
      title: 'Conservation Volunteers NZ - Hands-On Conservation',
      organization: 'Conservation Volunteers New Zealand (CVNZ)',
      organizationUrl: 'https://www.conservationvolunteers.co.nz/',
      description: 'Join practical conservation projects planting native trees, controlling invasive pests, and protecting endangered species. Work alongside experienced rangers in some of NZ\'s most important ecosystems. No prior experience needed — full training and equipment provided.',
      location: 'Auckland / Wellington / Christchurch, New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['volunteering', 'conservation', 'environment', 'planting', 'pest-control'],
      skills: ['teamwork', 'fieldwork', 'environmental-science'],
      category: 'Conservation',
      url: 'https://www.conservationvolunteers.co.nz/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 1 * day).toISOString(),
      benefits: ['Outdoor experience', 'Training provided', 'Meet like-minded people'],
    },
    {
      id: 'vol_cvnz_nature_champions',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'cvnz_nature_champions',
      title: 'CVNZ Nature Champions Programme',
      organization: 'Conservation Volunteers New Zealand (CVNZ)',
      organizationUrl: 'https://conservationvolunteers.co.nz/nature-champions/',
      description: 'An immersive week-long conservation programme where you live and work alongside other volunteers at biodiversity-critical sites. Accommodation and meals included. Ideal for anyone wanting a deeper dive into conservation work across Auckland, Wellington, or Christchurch.',
      location: 'Auckland / Wellington / Christchurch, New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['volunteering', 'conservation', 'immersive', 'biodiversity', 'residential'],
      skills: ['teamwork', 'fieldwork', 'resilience', 'environmental-science'],
      category: 'Conservation',
      url: 'https://conservationvolunteers.co.nz/nature-champions/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 3 * day).toISOString(),
      benefits: ['Accommodation included', 'Meals provided', 'Intensive training', 'Certificate of participation'],
    },
    {
      id: 'vol_zealandia_wellington',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'zealandia_vol',
      title: 'Zealandia Ecosanctuary Volunteer',
      organization: 'Zealandia Te Māra a Tāne',
      organizationUrl: 'https://www.visitzealandia.com',
      description: 'Support Wellington\'s world-leading urban ecosanctuary with track maintenance, ranger assistance, and fenceline management. Must be 18+ with a police check. A rare chance to work within a predator-free wildlife sanctuary home to tuatara, kākā, and takahē.',
      location: 'Wellington, New Zealand',
      locationType: 'onsite',
      city: 'Wellington',
      country: 'New Zealand',
      tags: ['volunteering', 'conservation', 'wildlife', 'sanctuary', 'wellington'],
      skills: ['fieldwork', 'physical-fitness', 'teamwork'],
      category: 'Conservation',
      url: 'https://www.visitzealandia.com/Volunteer',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 5 * day).toISOString(),
      benefits: ['Work in predator-free sanctuary', 'Wildlife encounters', 'Training provided'],
    },
    {
      id: 'vol_cvnz_nursery_chch',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'cvnz_nursery_chch',
      title: 'CVNZ Community Native Plant Nursery Christchurch',
      organization: 'Conservation Volunteers New Zealand (CVNZ)',
      organizationUrl: 'https://www.conservationvolunteers.co.nz/',
      description: 'Help pot and grow native seedlings at the Climate Action Campus nursery in Christchurch. These plants go on to restore local habitats and enhance urban biodiversity. A relaxed, social volunteering experience suitable for all ages and abilities.',
      location: 'Christchurch, New Zealand',
      locationType: 'onsite',
      city: 'Christchurch',
      country: 'New Zealand',
      tags: ['volunteering', 'conservation', 'planting', 'nursery', 'christchurch'],
      skills: ['gardening', 'teamwork', 'attention-to-detail'],
      category: 'Conservation',
      url: 'https://conservationvolunteers.co.nz/2026/01/08/community-native-plant-nursery-in-christchurch/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 9 * day).toISOString(),
      benefits: ['Learn native plant propagation', 'Social environment', 'No experience needed'],
    },
    {
      id: 'vol_scanz_student',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'scanz_student_vol',
      title: 'SCANZ Conference Student Volunteer',
      organization: 'Science Communicators\' Association of NZ (SCANZ)',
      organizationUrl: 'https://www.scanz.co.nz',
      description: 'Volunteer at NZ\'s premier science communication conference in Christchurch, 24–26 June 2026. Assist with event logistics, speaker support, and attendee registration. Free conference registration for volunteers — an excellent networking opportunity for STEM students.',
      location: 'Christchurch, New Zealand',
      locationType: 'onsite',
      city: 'Christchurch',
      country: 'New Zealand',
      tags: ['volunteering', 'science-communication', 'conference', 'STEM', 'events'],
      skills: ['event-management', 'communication', 'organisation'],
      category: 'Events',
      url: 'https://www.scanz.co.nz/student-volunteers',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      benefits: ['Free conference registration', 'Networking with scientists', 'Event experience'],
    },
    {
      id: 'vol_auckland_city_mission',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'akl_city_mission',
      title: 'Auckland City Mission Volunteer',
      organization: 'Auckland City Mission',
      organizationUrl: 'https://www.aucklandcitymission.org.nz',
      description: 'Support Auckland\'s most vulnerable communities through the food bank, community meals programme, and wrap-around support services. Roles range from food sorting and meal prep to front-of-house client support. Flexible shifts available throughout the week.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['volunteering', 'community', 'food-bank', 'social-services', 'auckland'],
      skills: ['communication', 'empathy', 'teamwork', 'food-handling'],
      category: 'Community Service',
      url: 'https://www.aucklandcitymission.org.nz/get-involved/volunteer/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      benefits: ['Flexible shifts', 'Direct community impact', 'Training provided'],
    },
    {
      id: 'vol_kidscan',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'kidscan_vol',
      title: 'KidsCan Volunteer',
      organization: 'KidsCan Charitable Trust',
      organizationUrl: 'https://www.kidscan.org.nz',
      description: 'Help Kiwi kids living in poverty by packing food parcels, sorting donated clothing and health products, and assisting with fundraising events. KidsCan supports over 900 schools across New Zealand, and volunteers are essential to keeping the programme running.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['volunteering', 'children', 'poverty', 'food', 'community'],
      skills: ['teamwork', 'organisation', 'empathy'],
      category: 'Community Service',
      url: 'https://www.kidscan.org.nz/get-involved/volunteer',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 11 * day).toISOString(),
      benefits: ['Meaningful impact on children', 'Team environment', 'Flexible commitment'],
    },
    {
      id: 'vol_blind_low_vision',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'blind_lv_vol',
      title: 'Blind Low Vision NZ Volunteer',
      organization: 'Blind Low Vision NZ',
      organizationUrl: 'https://blindlowvision.org.nz',
      description: 'Provide vital support to New Zealanders with vision loss. Roles include reading services, transport assistance to appointments, technology mentoring, and companionship visits. Full orientation and ongoing support provided to all volunteers.',
      location: 'Multiple locations, New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['volunteering', 'disability', 'accessibility', 'reading', 'technology'],
      skills: ['communication', 'patience', 'empathy', 'technology'],
      category: 'Disability Support',
      url: 'https://blindlowvision.org.nz/get-involved/volunteer/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 12 * day).toISOString(),
      benefits: ['Training provided', 'Flexible hours', 'Meaningful one-on-one impact'],
    },
    {
      id: 'vol_spca_nz',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'spca_nz_vol',
      title: 'SPCA NZ Volunteer',
      organization: 'SPCA New Zealand',
      organizationUrl: 'https://www.spca.nz',
      description: 'Help protect and care for animals across Aotearoa. Shelter-based roles include dog walking, cat socialisation, small animal enrichment, and kennel cleaning. Community roles cover fostering, fundraising events, and education outreach.',
      location: 'Multiple locations, New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['volunteering', 'animals', 'welfare', 'shelter', 'fostering'],
      skills: ['animal-care', 'teamwork', 'communication'],
      category: 'Animal Welfare',
      url: 'https://www.spca.nz/get-involved/volunteer',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 7 * day).toISOString(),
      benefits: ['Work with animals', 'Training provided', 'Flexible roles'],
    },
    {
      id: 'vol_surf_lifesaving',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'slsnz_vol',
      title: 'Surf Life Saving NZ Volunteer',
      organization: 'Surf Life Saving New Zealand',
      organizationUrl: 'https://www.surflifesaving.org.nz',
      description: 'Join one of NZ\'s most iconic volunteer organisations. Patrol beaches, gain nationally recognised lifeguard qualifications, and deliver water safety education in schools and communities. Clubs operate in coastal locations nationwide.',
      location: 'Coastal locations, New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['volunteering', 'beach', 'lifeguard', 'water-safety', 'fitness'],
      skills: ['swimming', 'first-aid', 'fitness', 'teamwork', 'leadership'],
      category: 'Emergency Services',
      url: 'https://www.surflifesaving.org.nz/volunteering',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 8 * day).toISOString(),
      benefits: ['Lifeguard qualifications', 'Fitness training', 'Community belonging', 'Leadership development'],
    },
    {
      id: 'vol_forest_bird',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'forest_bird_vol',
      title: 'Forest & Bird Conservation Volunteer',
      organization: 'Royal Forest and Bird Protection Society of NZ',
      organizationUrl: 'https://www.forestandbird.org.nz',
      description: 'NZ\'s oldest and largest conservation organisation. Join local branch projects including pest trapping, native habitat restoration, beach clean-ups, and advocacy campaigns. A great way to make a hands-on difference for native birds and forests.',
      location: 'Multiple locations, New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['volunteering', 'conservation', 'pest-trapping', 'habitat-restoration', 'advocacy'],
      skills: ['fieldwork', 'teamwork', 'environmental-science'],
      category: 'Conservation',
      url: 'https://www.forestandbird.org.nz/get-involved/volunteer',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 13 * day).toISOString(),
      benefits: ['Local branch community', 'Outdoor activities', 'Conservation training'],
    },
    {
      id: 'vol_refugee_council',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'refugee_council_vol',
      title: 'Refugee Council NZ Volunteer',
      organization: 'New Zealand Refugee Council',
      organizationUrl: 'https://www.refugeecouncil.org.nz',
      description: 'Support newly arrived refugee and migrant families as they settle into life in Aotearoa. Roles include English conversation practice, navigating community services, driving to appointments, and helping children with homework.',
      location: 'Multiple locations, New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['volunteering', 'refugee', 'migrant', 'settlement', 'cultural'],
      skills: ['communication', 'cultural-awareness', 'empathy', 'patience'],
      category: 'Refugee Support',
      url: 'https://www.refugeecouncil.org.nz/get-involved/volunteer',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 14 * day).toISOString(),
      benefits: ['Cross-cultural experience', 'Training provided', 'Meaningful relationships'],
    },
    {
      id: 'vol_stjohn_youth',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'stjohn_youth_vol',
      title: 'St John Youth Programme',
      organization: 'St John New Zealand',
      organizationUrl: 'https://www.stjohn.org.nz',
      description: 'Gain practical first aid skills and volunteer at community events through NZ\'s leading emergency ambulance service. Youth members aged 6–18 learn CPR, patient assessment, and emergency response through weekly sessions and real-world duties at public events.',
      location: 'Multiple locations, New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['volunteering', 'first-aid', 'emergency', 'youth', 'health'],
      skills: ['first-aid', 'leadership', 'communication', 'crisis-response'],
      category: 'Emergency Services',
      url: 'https://www.stjohn.org.nz/what-we-do/youth/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 9 * day).toISOString(),
      benefits: ['First aid certification', 'Leadership development', 'Real emergency experience'],
    },
    {
      id: 'vol_recreate_nz',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'recreate_vol',
      title: 'Recreate NZ Volunteer',
      organization: 'Recreate NZ',
      organizationUrl: 'https://recreate.org.nz',
      description: 'Divert waste from landfill by sorting, upcycling, and redistributing donated materials for creative reuse. Help run community workshops teaching people to turn discarded items into art, craft, and learning resources. Based at the Auckland warehouse.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['volunteering', 'environment', 'upcycling', 'creative', 'sustainability'],
      skills: ['creativity', 'teamwork', 'organisation'],
      category: 'Environment',
      url: 'https://recreate.org.nz/volunteer/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 2 * day).toISOString(),
      benefits: ['Creative environment', 'Sustainability impact', 'Workshop facilitation experience'],
    },
    {
      id: 'vol_trees_that_count',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'ttc_vol',
      title: 'Trees That Count Planting Volunteer',
      organization: 'Trees That Count',
      organizationUrl: 'https://www.treesthatcount.co.nz',
      description: 'Participate in native tree planting events across New Zealand. Each tree is GPS-registered and tracked for survival, so your effort is measurable. Projects range from urban revegetation to large-scale riparian planting on farmland.',
      location: 'Multiple locations, New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['volunteering', 'environment', 'planting', 'native-trees', 'climate'],
      skills: ['fieldwork', 'teamwork', 'physical-fitness'],
      category: 'Conservation',
      url: 'https://www.treesthatcount.co.nz/get-involved',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 10 * day).toISOString(),
      benefits: ['Trackable impact', 'Outdoor experience', 'Community planting days'],
    },
    {
      id: 'vol_coastguard_nz',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'coastguard_vol',
      title: 'Coastguard NZ Volunteer',
      organization: 'Coastguard New Zealand',
      organizationUrl: 'https://www.coastguard.nz',
      description: 'Train as a marine rescue volunteer and help save lives on the water. Coastguard units across NZ respond to boating emergencies, deliver boating education, and conduct search and rescue operations. Full training in navigation, radio, and rescue techniques provided.',
      location: 'Coastal locations, New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['volunteering', 'marine', 'rescue', 'boating-safety', 'emergency'],
      skills: ['navigation', 'teamwork', 'communication', 'first-aid'],
      category: 'Emergency Services',
      url: 'https://www.coastguard.nz/volunteer/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 15 * day).toISOString(),
      benefits: ['Marine rescue training', 'Boating qualifications', 'Lifesaving impact'],
    },
    {
      id: 'vol_wellington_spca',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'wgtn_spca_vol',
      title: 'Wellington SPCA Volunteer',
      organization: 'Wellington SPCA',
      organizationUrl: 'https://www.wellingtonspca.org.nz',
      description: 'Volunteer at Wellington\'s animal shelter in Newtown. Walk dogs, socialise cats, assist with adoption days, and help at fundraising events. A rewarding way to improve animal welfare while gaining hands-on experience with animal care.',
      location: 'Wellington, New Zealand',
      locationType: 'onsite',
      city: 'Wellington',
      country: 'New Zealand',
      tags: ['volunteering', 'animals', 'shelter', 'wellington', 'welfare'],
      skills: ['animal-care', 'communication', 'teamwork'],
      category: 'Animal Welfare',
      url: 'https://www.wellingtonspca.org.nz/get-involved/volunteer/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 6 * day).toISOString(),
      benefits: ['Animal interaction', 'Flexible shifts', 'Feel-good impact'],
    },
    {
      id: 'vol_dress_for_success_akl',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'dfs_akl_vol',
      title: 'Dress for Success Auckland Volunteer',
      organization: 'Dress for Success Auckland',
      organizationUrl: 'https://auckland.dressforsuccess.org',
      description: 'Empower women entering or re-entering the workforce by helping with professional styling, interview coaching, and career mentoring. Volunteers sort donated professional clothing and deliver one-on-one styling sessions that build confidence.',
      location: 'Auckland, New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['volunteering', 'women', 'empowerment', 'career', 'fashion'],
      skills: ['communication', 'empathy', 'mentoring', 'organisation'],
      category: 'Community Service',
      url: 'https://auckland.dressforsuccess.org/get-involved/volunteer/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 11 * day).toISOString(),
      benefits: ['Empower women', 'Mentoring experience', 'Professional development'],
    },
    {
      id: 'vol_kaipatiki_akl',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'kaipatiki_vol',
      title: 'Kaipatiki Project Community Conservation',
      organization: 'Kaipatiki Project',
      organizationUrl: 'https://www.kaipatiki.org.nz',
      description: 'Join Auckland\'s North Shore urban conservation community. Activities include native bush restoration, community garden maintenance, stream monitoring, and environmental education workshops. Regular weekly volunteer sessions in local reserves.',
      location: 'Auckland (North Shore), New Zealand',
      locationType: 'onsite',
      city: 'Auckland',
      country: 'New Zealand',
      tags: ['volunteering', 'conservation', 'urban', 'gardening', 'auckland'],
      skills: ['gardening', 'teamwork', 'environmental-science'],
      category: 'Conservation',
      url: 'https://www.kaipatiki.org.nz/volunteer/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 4 * day).toISOString(),
      benefits: ['Regular weekly sessions', 'Local community', 'Learn native ecology'],
    },
    {
      id: 'vol_predator_free_nz',
      type: 'volunteering',
      source: 'curated',
      sourceId: 'pfnz_vol',
      title: 'Predator Free NZ Volunteer',
      organization: 'Predator Free NZ Trust',
      organizationUrl: 'https://predatorfreenz.org',
      description: 'Help make New Zealand predator free by 2050. Set up and maintain backyard trap lines, monitor bait stations, record pest catches, and help coordinate community trapping networks. Training and trap equipment provided for new volunteers.',
      location: 'Multiple locations, New Zealand',
      locationType: 'onsite',
      country: 'New Zealand',
      tags: ['volunteering', 'conservation', 'pest-control', 'trapping', 'wildlife-protection'],
      skills: ['fieldwork', 'data-collection', 'teamwork'],
      category: 'Conservation',
      url: 'https://predatorfreenz.org/get-involved/',
      applicationType: 'external',
      status: 'active',
      createdAt: new Date(now - 13 * day).toISOString(),
      benefits: ['Traps and equipment provided', 'Training included', 'Protect native wildlife'],
    },
  ];
}

export const volunteeringConnector: OpportunityConnector = {
  name: 'volunteering',
  supportedTypes: ['volunteering'],
  async fetch(config): Promise<ConnectorResult> {
    const errors: string[] = [];
    let opportunities: Opportunity[] = [];

    try {
      const live = await fetchSeekVolunteer();
      opportunities.push(...live);
      console.log(`[VolunteeringConnector] Scraped ${live.length} from Seek Volunteer`);
    } catch (err) {
      errors.push(`SeekVolunteer: ${String(err)}`);
    }

    opportunities.push(...getCuratedVolunteering());

    if (config.maxResults) {
      opportunities = opportunities.slice(0, config.maxResults);
    }

    return {
      opportunities,
      source: 'volunteering',
      fetchedAt: new Date().toISOString(),
      stats: { fetched: opportunities.length, validated: opportunities.length, errors },
    };
  },
};
